-- ============================================================================
-- 0013 · SPRINT 2: Compras, Proveedores y Tesorería
--
-- Se apoya sobre el esquema del Sprint 1 ya existente. NO crea las tablas de
-- stock: las asume presentes. Las tablas recepciones y detalle_recepcion, que
-- se crearon en 0011, se extienden con ALTER TABLE en vez de recrearse.
--
-- Convención de estados: minúscula y snake_case ('parcialmente_recibida').
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 0. FUNCIÓN AUXILIAR
-- ----------------------------------------------------------------------------

create or replace function public.fn_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;


-- ============================================================================
-- 1. PROVEEDORES
-- ============================================================================

create table if not exists public.rubros_proveedor (
  id          uuid primary key default gen_random_uuid(),
  nombre      text not null,
  activo      boolean not null default true,
  created_at  timestamptz not null default now(),
  constraint uq_rubro_nombre unique (nombre),
  constraint chk_rubro_nombre_no_vacio check (length(trim(nombre)) > 0)
);

create table if not exists public.proveedores (
  id                       uuid primary key default gen_random_uuid(),
  razon_social             text not null,
  cuit                     text not null,
  condicion_fiscal         text not null,
  condicion_pago_habitual  text,
  domicilio                text,
  localidad                text,
  estado                   text not null default 'activo',
  created_by               uuid default auth.uid() references auth.users(id),
  updated_by               uuid references auth.users(id),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  constraint uq_proveedor_cuit  unique (cuit),
  constraint chk_proveedor_cuit check (cuit ~ '^[0-9]{11}$'),
  constraint chk_proveedor_estado check (estado in ('activo','inactivo')),
  constraint chk_proveedor_razon_social check (length(trim(razon_social)) > 0)
);

drop trigger if exists trg_proveedores_updated_at on public.proveedores;
create trigger trg_proveedores_updated_at
  before update on public.proveedores
  for each row execute function public.fn_set_updated_at();

create table if not exists public.proveedor_rubro (
  proveedor_id  uuid not null references public.proveedores(id) on delete cascade,
  rubro_id      uuid not null references public.rubros_proveedor(id) on delete restrict,
  created_at    timestamptz not null default now(),
  primary key (proveedor_id, rubro_id)
);

create table if not exists public.contactos_proveedor (
  id            uuid primary key default gen_random_uuid(),
  proveedor_id  uuid not null references public.proveedores(id) on delete cascade,
  nombre        text not null,
  cargo         text,
  telefono      text,
  email         text,
  principal     boolean not null default false,
  activo        boolean not null default true,
  created_at    timestamptz not null default now(),
  constraint chk_contacto_email check (email is null or email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

create unique index if not exists ux_contacto_principal
  on public.contactos_proveedor (proveedor_id)
  where principal;


-- ============================================================================
-- 2. COMPRAS: solicitudes y órdenes
-- ============================================================================

create table if not exists public.solicitudes_reposicion (
  id             uuid primary key default gen_random_uuid(),
  numero         bigint generated by default as identity,
  deposito_id    uuid not null references public.depositos(id) on delete restrict,
  origen         text not null default 'manual',
  estado         text not null default 'pendiente',
  aprobado_by    uuid references auth.users(id),
  aprobado_at    timestamptz,
  motivo_rechazo text,
  created_by     uuid default auth.uid() references auth.users(id),
  created_at     timestamptz not null default now(),
  constraint uq_solicitud_numero unique (numero),
  constraint chk_solicitud_origen check (origen in ('manual','stock_minimo')),
  constraint chk_solicitud_estado check (estado in ('pendiente','aprobada','rechazada','convertida','anulada')),
  constraint chk_solicitud_aprobacion check (
    estado <> 'aprobada' or (aprobado_by is not null and aprobado_at is not null)
  )
);

create table if not exists public.detalle_solicitud_reposicion (
  id                   uuid primary key default gen_random_uuid(),
  solicitud_id         uuid not null references public.solicitudes_reposicion(id) on delete cascade,
  producto_id          uuid not null references public.productos(id),
  cantidad_sugerida    numeric,
  cantidad_solicitada  numeric not null,
  estado               text not null default 'pendiente',
  created_at           timestamptz not null default now(),
  constraint uq_detalle_solicitud unique (solicitud_id, producto_id),
  constraint chk_detalle_solicitud_cantidad check (cantidad_solicitada > 0),
  constraint chk_detalle_solicitud_estado check (estado in ('pendiente','parcial','convertida','anulada'))
);

create table if not exists public.ordenes_compra (
  id                      uuid primary key default gen_random_uuid(),
  numero                  bigint generated by default as identity,
  solicitud_id            uuid references public.solicitudes_reposicion(id),
  proveedor_id            uuid not null references public.proveedores(id) on delete restrict,
  deposito_destino_id     uuid not null references public.depositos(id) on delete restrict,
  condicion_pago          text,
  fecha_emision           date not null default current_date,
  fecha_entrega_estimada  date,
  estado                  text not null default 'pendiente',
  total                   numeric(14,2) not null default 0,
  observaciones           text,
  cancelado_by            uuid references auth.users(id),
  cancelado_at            timestamptz,
  motivo_cancelacion      text,
  created_by              uuid default auth.uid() references auth.users(id),
  updated_by              uuid references auth.users(id),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  constraint uq_oc_numero unique (numero),
  constraint chk_oc_estado check (estado in ('pendiente','parcialmente_recibida','recibida','cancelada')),
  constraint chk_oc_fechas check (fecha_entrega_estimada is null or fecha_entrega_estimada >= fecha_emision),
  constraint chk_oc_cancelacion check (
    estado <> 'cancelada' or (cancelado_by is not null and motivo_cancelacion is not null)
  ),
  constraint chk_oc_observaciones_no_vacio check (observaciones is null or length(btrim(observaciones)) > 0)
);

drop trigger if exists trg_oc_updated_at on public.ordenes_compra;
create trigger trg_oc_updated_at
  before update on public.ordenes_compra
  for each row execute function public.fn_set_updated_at();

create table if not exists public.detalle_orden_compra (
  id                    uuid primary key default gen_random_uuid(),
  orden_compra_id       uuid not null references public.ordenes_compra(id) on delete cascade,
  solicitud_detalle_id  uuid references public.detalle_solicitud_reposicion(id),
  producto_id           uuid not null references public.productos(id),
  cantidad              numeric not null,
  precio_unitario       numeric not null,
  subtotal              numeric generated always as (cantidad * precio_unitario) stored,
  created_at            timestamptz not null default now(),
  constraint uq_detalle_oc unique (orden_compra_id, producto_id),
  constraint chk_detalle_oc_cantidad check (cantidad > 0),
  constraint chk_detalle_oc_precio check (precio_unitario > 0)
);


-- ============================================================================
-- 3. EXTENSIÓN DE recepciones Y detalle_recepcion (creadas en 0011)
-- ============================================================================

-- Las 3 filas existentes eran de prueba y no tienen forma de resolver el
-- proveedor, porque ordenes_compra no existía cuando se cargaron.
delete from public.detalle_recepcion;
delete from public.recepciones;

alter table public.recepciones
  add column if not exists numero                  bigint generated by default as identity,
  add column if not exists tipo_origen             text,
  add column if not exists proveedor_id            uuid,
  add column if not exists remito_proveedor        text,
  add column if not exists fecha_recepcion         date not null default current_date,
  add column if not exists movimiento_ingreso_id   uuid,
  add column if not exists movimiento_anulacion_id uuid,
  add column if not exists motivo_compra_directa   text,
  add column if not exists anulado_by              uuid,
  add column if not exists anulado_at              timestamptz,
  add column if not exists motivo_anulacion        text;

-- tipo_origen y proveedor_id son obligatorios de acá en adelante.
alter table public.recepciones
  alter column tipo_origen  set not null,
  alter column proveedor_id set not null;

-- El CHECK original solo admitía 'pendiente' y 'confirmada'. La HU4 exige
-- poder anular una recepción, así que hay que reemplazarlo.
alter table public.recepciones drop constraint if exists recepciones_estado_check;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'uq_recepcion_numero') then
    alter table public.recepciones add constraint uq_recepcion_numero unique (numero);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'recepciones_orden_compra_id_fkey') then
    alter table public.recepciones
      add constraint recepciones_orden_compra_id_fkey
      foreign key (orden_compra_id) references public.ordenes_compra(id) on delete restrict;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'recepciones_proveedor_id_fkey') then
    alter table public.recepciones
      add constraint recepciones_proveedor_id_fkey
      foreign key (proveedor_id) references public.proveedores(id) on delete restrict;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'recepciones_mov_ingreso_fkey') then
    alter table public.recepciones
      add constraint recepciones_mov_ingreso_fkey
      foreign key (movimiento_ingreso_id) references public.movimientos_stock(id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'recepciones_mov_anulacion_fkey') then
    alter table public.recepciones
      add constraint recepciones_mov_anulacion_fkey
      foreign key (movimiento_anulacion_id) references public.movimientos_stock(id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'recepciones_anulado_by_fkey') then
    alter table public.recepciones
      add constraint recepciones_anulado_by_fkey
      foreign key (anulado_by) references auth.users(id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'chk_recepcion_estado') then
    alter table public.recepciones add constraint chk_recepcion_estado
      check (estado_recepcion in ('pendiente','confirmada','anulada'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'chk_recepcion_tipo_origen') then
    alter table public.recepciones add constraint chk_recepcion_tipo_origen
      check (tipo_origen in ('orden_compra','directa'));
  end if;

  -- HU15: compra directa no lleva OC y exige motivo. Con OC es al revés.
  if not exists (select 1 from pg_constraint where conname = 'chk_recepcion_coherencia_origen') then
    alter table public.recepciones add constraint chk_recepcion_coherencia_origen
      check (
        (tipo_origen = 'orden_compra' and orden_compra_id is not null and motivo_compra_directa is null)
        or
        (tipo_origen = 'directa' and orden_compra_id is null and motivo_compra_directa is not null)
      );
  end if;

  -- HU4: anular exige usuario y motivo.
  if not exists (select 1 from pg_constraint where conname = 'chk_recepcion_anulacion') then
    alter table public.recepciones add constraint chk_recepcion_anulacion
      check (
        estado_recepcion <> 'anulada'
        or (anulado_by is not null and motivo_anulacion is not null)
      );
  end if;
end $$;

-- Permite comparar lo recibido contra lo pedido en la OC.
alter table public.detalle_recepcion
  add column if not exists orden_compra_detalle_id uuid;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'detalle_recepcion_det_oc_fkey') then
    alter table public.detalle_recepcion
      add constraint detalle_recepcion_det_oc_fkey
      foreign key (orden_compra_detalle_id) references public.detalle_orden_compra(id);
  end if;
end $$;


-- ============================================================================
-- 4. DEVOLUCIONES
-- ============================================================================

create table if not exists public.devoluciones_proveedor (
  id                       uuid primary key default gen_random_uuid(),
  numero                   bigint generated by default as identity,
  recepcion_id             uuid not null references public.recepciones(id) on delete restrict,
  proveedor_id             uuid not null references public.proveedores(id) on delete restrict,
  movimiento_egreso_id     uuid references public.movimientos_stock(id),
  movimiento_reposicion_id uuid references public.movimientos_stock(id),
  fecha                    date not null default current_date,
  motivo                   text not null,
  estado_acuerdo           text not null default 'pendiente',
  created_by               uuid default auth.uid() references auth.users(id),
  created_at               timestamptz not null default now(),
  constraint uq_devolucion_numero unique (numero),
  constraint chk_devolucion_estado check (estado_acuerdo in ('pendiente','acreditada','repuesta')),
  constraint chk_devolucion_motivo_no_vacio check (length(btrim(motivo)) > 0)
);

create table if not exists public.detalle_devolucion (
  id                    uuid primary key default gen_random_uuid(),
  devolucion_id         uuid not null references public.devoluciones_proveedor(id) on delete cascade,
  detalle_recepcion_id  uuid not null references public.detalle_recepcion(id),
  cantidad              numeric not null,
  created_at            timestamptz not null default now(),
  constraint chk_detalle_devolucion_cantidad check (cantidad > 0)
);


-- ============================================================================
-- 5. TESORERÍA
-- ============================================================================

create table if not exists public.facturas_proveedor (
  id                uuid primary key default gen_random_uuid(),
  proveedor_id      uuid not null references public.proveedores(id) on delete restrict,
  tipo_comprobante  text not null,
  punto_venta       text not null,
  numero            text not null,
  fecha_emision     date not null,
  fecha_vencimiento date,
  importe_neto      numeric(14,2) not null default 0,
  impuestos         numeric(14,2) not null default 0,
  importe_total     numeric(14,2) not null,
  saldo_pendiente   numeric(14,2) not null default 0,
  estado            text not null default 'pendiente',
  anulado_by        uuid references auth.users(id),
  anulado_at        timestamptz,
  motivo_anulacion  text,
  created_by        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now(),
  constraint uq_factura_comprobante unique (proveedor_id, tipo_comprobante, punto_venta, numero),
  constraint chk_factura_tipo check (tipo_comprobante in ('factura_a','factura_b','factura_c','factura_m','otro')),
  constraint chk_factura_estado check (estado in ('pendiente','parcialmente_pagada','pagada','anulada')),
  constraint chk_factura_importe check (importe_total > 0),
  constraint chk_factura_saldo check (saldo_pendiente >= 0 and saldo_pendiente <= importe_total),
  constraint chk_factura_fechas check (fecha_vencimiento is null or fecha_vencimiento >= fecha_emision),
  constraint chk_factura_anulacion check (
    estado <> 'anulada' or (anulado_by is not null and motivo_anulacion is not null)
  )
);

-- Sin esta tabla no se puede cumplir la HU3: comparar precio unitario facturado
-- contra el pactado, y cantidad facturada contra la efectivamente recibida.
create table if not exists public.detalle_factura_proveedor (
  id                       uuid primary key default gen_random_uuid(),
  factura_id               uuid not null references public.facturas_proveedor(id) on delete cascade,
  detalle_recepcion_id     uuid references public.detalle_recepcion(id),
  detalle_orden_compra_id  uuid references public.detalle_orden_compra(id),
  producto_id              uuid not null references public.productos(id),
  cantidad                 numeric not null,
  precio_unitario          numeric not null,
  subtotal                 numeric generated always as (cantidad * precio_unitario) stored,
  created_at               timestamptz not null default now(),
  constraint chk_detalle_factura_cantidad check (cantidad > 0),
  constraint chk_detalle_factura_precio check (precio_unitario > 0)
);

-- Una factura puede cubrir varias recepciones y viceversa.
create table if not exists public.factura_recepcion (
  factura_id    uuid not null references public.facturas_proveedor(id) on delete cascade,
  recepcion_id  uuid not null references public.recepciones(id) on delete restrict,
  created_at    timestamptz not null default now(),
  primary key (factura_id, recepcion_id)
);

create table if not exists public.notas_credito_proveedor (
  id                uuid primary key default gen_random_uuid(),
  proveedor_id      uuid not null references public.proveedores(id) on delete restrict,
  devolucion_id     uuid references public.devoluciones_proveedor(id),
  tipo              text not null,
  punto_venta       text not null,
  numero            text not null,
  fecha             date not null default current_date,
  importe           numeric(14,2) not null,
  saldo_pendiente   numeric(14,2) not null default 0,
  tipo_motivo       text not null,
  motivo            text,
  estado            text not null default 'pendiente',
  anulado_by        uuid references auth.users(id),
  anulado_at        timestamptz,
  motivo_anulacion  text,
  created_by        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now(),
  constraint uq_nc_comprobante unique (proveedor_id, tipo, punto_venta, numero),
  constraint chk_nc_tipo check (tipo in ('nota_credito_a','nota_credito_b','nota_credito_c','otro')),
  constraint chk_nc_importe check (importe > 0),
  constraint chk_nc_saldo check (saldo_pendiente >= 0 and saldo_pendiente <= importe),
  constraint chk_nc_tipo_motivo check (tipo_motivo in ('devolucion','diferencia_facturacion','bonificacion','otro')),
  constraint chk_nc_estado check (estado in ('pendiente','parcialmente_aplicada','aplicada','anulada')),
  constraint chk_nc_anulacion check (
    estado <> 'anulada' or (anulado_by is not null and motivo_anulacion is not null)
  )
);

create table if not exists public.medios_pago (
  id          uuid primary key default gen_random_uuid(),
  nombre      text not null unique,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.pagos_proveedor (
  id                uuid primary key default gen_random_uuid(),
  numero            bigint generated by default as identity,
  proveedor_id      uuid not null references public.proveedores(id) on delete restrict,
  medio_pago_id     uuid not null references public.medios_pago(id) on delete restrict,
  fecha             date not null default current_date,
  importe_total     numeric(14,2) not null,
  referencia        text,
  estado            text not null default 'registrado',
  anulado_by        uuid references auth.users(id),
  anulado_at        timestamptz,
  motivo_anulacion  text,
  created_by        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now(),
  constraint uq_pago_numero unique (numero),
  constraint chk_pago_importe check (importe_total > 0),
  constraint chk_pago_estado check (estado in ('registrado','anulado')),
  constraint chk_pago_anulacion check (
    estado <> 'anulado' or (anulado_by is not null and motivo_anulacion is not null)
  )
);

-- Imputación generalizada: sirve tanto para pagos como para notas de crédito.
-- El CHECK garantiza un único origen por fila, manteniendo FKs reales.
create table if not exists public.imputaciones (
  id                uuid primary key default gen_random_uuid(),
  factura_id        uuid not null references public.facturas_proveedor(id) on delete restrict,
  pago_id           uuid references public.pagos_proveedor(id) on delete cascade,
  nota_credito_id   uuid references public.notas_credito_proveedor(id) on delete cascade,
  importe_imputado  numeric(14,2) not null,
  created_at        timestamptz not null default now(),
  constraint chk_imputacion_importe check (importe_imputado > 0),
  constraint chk_imputacion_origen_unico check (num_nonnulls(pago_id, nota_credito_id) = 1)
);

create unique index if not exists ux_imputacion_pago_factura
  on public.imputaciones (pago_id, factura_id) where pago_id is not null;

create unique index if not exists ux_imputacion_nc_factura
  on public.imputaciones (nota_credito_id, factura_id) where nota_credito_id is not null;


-- ============================================================================
-- 6. REGLAS DE NEGOCIO
-- ============================================================================

create or replace function public.fn_recalcular_total_oc()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_oc uuid := coalesce(new.orden_compra_id, old.orden_compra_id);
begin
  update public.ordenes_compra
     set total = coalesce((
           select sum(subtotal) from public.detalle_orden_compra where orden_compra_id = v_oc
         ), 0)
   where id = v_oc;
  return null;
end;
$$;

drop trigger if exists trg_recalcular_total_oc on public.detalle_orden_compra;
create trigger trg_recalcular_total_oc
  after insert or update or delete on public.detalle_orden_compra
  for each row execute function public.fn_recalcular_total_oc();


create or replace function public.fn_init_saldo_factura()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.saldo_pendiente is null or new.saldo_pendiente = 0 then
    new.saldo_pendiente := new.importe_total;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_init_saldo_factura on public.facturas_proveedor;
create trigger trg_init_saldo_factura
  before insert on public.facturas_proveedor
  for each row execute function public.fn_init_saldo_factura();


create or replace function public.fn_init_saldo_nc()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.saldo_pendiente is null or new.saldo_pendiente = 0 then
    new.saldo_pendiente := new.importe;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_init_saldo_nc on public.notas_credito_proveedor;
create trigger trg_init_saldo_nc
  before insert on public.notas_credito_proveedor
  for each row execute function public.fn_init_saldo_nc();


-- Recalcula el saldo y el estado de una factura considerando únicamente las
-- imputaciones cuyo origen (pago o nota de crédito) NO está anulado.
-- HU13: al anular un pago se restituye el saldo pendiente de los comprobantes
-- que tenía imputados.
create or replace function public.fn_recalcular_saldo_factura(p_factura uuid)
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_importe  numeric(14,2);
  v_imputado numeric(14,2);
begin
  select importe_total into v_importe
    from public.facturas_proveedor where id = p_factura;

  if v_importe is null then
    return;
  end if;

  select coalesce(sum(i.importe_imputado),0) into v_imputado
    from public.imputaciones i
    left join public.pagos_proveedor pg          on pg.id = i.pago_id
    left join public.notas_credito_proveedor nc  on nc.id = i.nota_credito_id
   where i.factura_id = p_factura
     and coalesce(pg.estado, 'registrado') <> 'anulado'
     and coalesce(nc.estado, 'pendiente')  <> 'anulada';

  if v_imputado > v_importe then
    raise exception 'La suma imputada (%) supera el importe de la factura (%)', v_imputado, v_importe;
  end if;

  update public.facturas_proveedor
     set saldo_pendiente = importe_total - v_imputado,
         estado = case
                    when estado = 'anulada' then 'anulada'
                    when importe_total - v_imputado <= 0 then 'pagada'
                    when v_imputado > 0 then 'parcialmente_pagada'
                    else 'pendiente'
                  end
   where id = p_factura;
end;
$$;


-- Igual que la anterior, pero para el saldo de una nota de crédito.
create or replace function public.fn_recalcular_saldo_nc(p_nc uuid)
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_importe  numeric(14,2);
  v_imputado numeric(14,2);
begin
  select importe into v_importe
    from public.notas_credito_proveedor where id = p_nc;

  if v_importe is null then
    return;
  end if;

  select coalesce(sum(importe_imputado),0) into v_imputado
    from public.imputaciones where nota_credito_id = p_nc;

  if v_imputado > v_importe then
    raise exception 'La suma imputada (%) supera el importe de la nota de crédito (%)', v_imputado, v_importe;
  end if;

  update public.notas_credito_proveedor
     set saldo_pendiente = importe - v_imputado,
         estado = case
                    when estado = 'anulada' then 'anulada'
                    when importe - v_imputado <= 0 then 'aplicada'
                    when v_imputado > 0 then 'parcialmente_aplicada'
                    else 'pendiente'
                  end
   where id = p_nc;
end;
$$;


-- HU13: la suma imputada no puede superar el importe del pago ni el de la NC.
create or replace function public.fn_aplicar_imputacion()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_factura  uuid := coalesce(new.factura_id, old.factura_id);
  v_pago     uuid := coalesce(new.pago_id, old.pago_id);
  v_nc       uuid := coalesce(new.nota_credito_id, old.nota_credito_id);
  v_imputado numeric(14,2);
  v_importe  numeric(14,2);
begin
  if v_pago is not null then
    select importe_total into v_importe from public.pagos_proveedor where id = v_pago;
    select coalesce(sum(importe_imputado),0) into v_imputado
      from public.imputaciones where pago_id = v_pago;
    if v_imputado > v_importe then
      raise exception 'La suma imputada (%) supera el importe del pago (%)', v_imputado, v_importe;
    end if;
  end if;

  if v_nc is not null then
    perform public.fn_recalcular_saldo_nc(v_nc);
  end if;

  perform public.fn_recalcular_saldo_factura(v_factura);
  return null;
end;
$$;

drop trigger if exists trg_aplicar_imputacion on public.imputaciones;
create trigger trg_aplicar_imputacion
  after insert or update or delete on public.imputaciones
  for each row execute function public.fn_aplicar_imputacion();


-- HU13: anular un pago restituye el saldo de todas las facturas que tenía
-- imputadas. Lo mismo al anular una nota de crédito.
create or replace function public.fn_anulacion_restituye_saldo()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_factura uuid;
begin
  if tg_table_name = 'pagos_proveedor' then
    for v_factura in select distinct factura_id from public.imputaciones where pago_id = new.id
    loop
      perform public.fn_recalcular_saldo_factura(v_factura);
    end loop;
  else
    for v_factura in select distinct factura_id from public.imputaciones where nota_credito_id = new.id
    loop
      perform public.fn_recalcular_saldo_factura(v_factura);
    end loop;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_pago_anulado on public.pagos_proveedor;
create trigger trg_pago_anulado
  after update of estado on public.pagos_proveedor
  for each row when (old.estado is distinct from new.estado)
  execute function public.fn_anulacion_restituye_saldo();

drop trigger if exists trg_nc_anulada on public.notas_credito_proveedor;
create trigger trg_nc_anulada
  after update of estado on public.notas_credito_proveedor
  for each row when (old.estado is distinct from new.estado and new.estado = 'anulada')
  execute function public.fn_anulacion_restituye_saldo();


-- No se puede recibir más de lo pedido en la OC.
create or replace function public.fn_validar_cantidad_recibida()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_pedido   numeric;
  v_recibido numeric;
begin
  if new.orden_compra_detalle_id is null then
    return new;
  end if;

  select cantidad into v_pedido
    from public.detalle_orden_compra where id = new.orden_compra_detalle_id;

  select coalesce(sum(dr.cantidad),0) into v_recibido
    from public.detalle_recepcion dr
    join public.recepciones r on r.id = dr.recepcion_id
   where dr.orden_compra_detalle_id = new.orden_compra_detalle_id
     and r.estado_recepcion <> 'anulada'
     and dr.id <> new.id;

  if v_recibido + new.cantidad > v_pedido then
    raise exception 'La cantidad recibida (%) supera la pedida en la Orden de Compra (%)',
      v_recibido + new.cantidad, v_pedido;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validar_cantidad_recibida on public.detalle_recepcion;
create trigger trg_validar_cantidad_recibida
  before insert or update on public.detalle_recepcion
  for each row execute function public.fn_validar_cantidad_recibida();


-- No se puede devolver más de lo recibido en esa línea.
create or replace function public.fn_validar_cantidad_devuelta()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_recibido numeric;
  v_devuelto numeric;
begin
  select cantidad into v_recibido
    from public.detalle_recepcion where id = new.detalle_recepcion_id;

  select coalesce(sum(cantidad),0) into v_devuelto
    from public.detalle_devolucion
   where detalle_recepcion_id = new.detalle_recepcion_id and id <> new.id;

  if v_devuelto + new.cantidad > v_recibido then
    raise exception 'La cantidad devuelta (%) supera la recibida (%)',
      v_devuelto + new.cantidad, v_recibido;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validar_cantidad_devuelta on public.detalle_devolucion;
create trigger trg_validar_cantidad_devuelta
  before insert or update on public.detalle_devolucion
  for each row execute function public.fn_validar_cantidad_devuelta();


-- ============================================================================
-- 7. ÍNDICES
-- ============================================================================

create index if not exists ix_proveedores_estado        on public.proveedores (estado);
create index if not exists ix_proveedores_razon_social  on public.proveedores using gin (to_tsvector('spanish', razon_social));
create index if not exists ix_contactos_proveedor       on public.contactos_proveedor (proveedor_id);
create index if not exists ix_proveedor_rubro_rubro     on public.proveedor_rubro (rubro_id);

create index if not exists ix_solicitud_deposito        on public.solicitudes_reposicion (deposito_id);
create index if not exists ix_solicitud_estado          on public.solicitudes_reposicion (estado);
create index if not exists ix_det_solicitud_solicitud   on public.detalle_solicitud_reposicion (solicitud_id);
create index if not exists ix_det_solicitud_producto    on public.detalle_solicitud_reposicion (producto_id);

create index if not exists ix_oc_proveedor              on public.ordenes_compra (proveedor_id);
create index if not exists ix_oc_estado                 on public.ordenes_compra (estado);
create index if not exists ix_oc_fecha_emision          on public.ordenes_compra (fecha_emision);
create index if not exists ix_det_oc_orden              on public.detalle_orden_compra (orden_compra_id);
create index if not exists ix_det_oc_producto           on public.detalle_orden_compra (producto_id);

create index if not exists ix_recepcion_oc              on public.recepciones (orden_compra_id);
create index if not exists ix_recepcion_proveedor       on public.recepciones (proveedor_id);
create index if not exists ix_recepcion_estado          on public.recepciones (estado_recepcion);
create index if not exists ix_det_recepcion_det_oc      on public.detalle_recepcion (orden_compra_detalle_id);

create index if not exists ix_devolucion_recepcion      on public.devoluciones_proveedor (recepcion_id);
create index if not exists ix_devolucion_proveedor      on public.devoluciones_proveedor (proveedor_id);
create index if not exists ix_det_devolucion_devolucion on public.detalle_devolucion (devolucion_id);

create index if not exists ix_factura_proveedor         on public.facturas_proveedor (proveedor_id);
create index if not exists ix_factura_estado            on public.facturas_proveedor (estado);
create index if not exists ix_factura_vencimiento       on public.facturas_proveedor (fecha_vencimiento);
create index if not exists ix_det_factura_factura       on public.detalle_factura_proveedor (factura_id);
create index if not exists ix_det_factura_det_recepcion on public.detalle_factura_proveedor (detalle_recepcion_id);

create index if not exists ix_nc_proveedor              on public.notas_credito_proveedor (proveedor_id);
create index if not exists ix_nc_devolucion             on public.notas_credito_proveedor (devolucion_id);
create index if not exists ix_pago_proveedor            on public.pagos_proveedor (proveedor_id);
create index if not exists ix_pago_fecha                on public.pagos_proveedor (fecha);
create index if not exists ix_imputacion_factura        on public.imputaciones (factura_id);
create index if not exists ix_imputacion_pago           on public.imputaciones (pago_id);
create index if not exists ix_imputacion_nc             on public.imputaciones (nota_credito_id);


-- ============================================================================
-- 8. VISTAS
-- ============================================================================

-- HU14: cuenta corriente. Criterio contable: el proveedor es un pasivo, así que
-- las facturas van al HABER (aumentan la deuda) y los pagos y notas de crédito
-- al DEBE. saldo_acumulado positivo significa que le debemos al proveedor.
create or replace view public.vw_cuenta_corriente_proveedor as
with movimientos as (
  select f.proveedor_id,
         f.fecha_emision                         as fecha,
         'factura'::text                         as tipo_movimiento,
         f.id                                    as comprobante_id,
         concat_ws('-', f.punto_venta, f.numero) as comprobante,
         0::numeric(14,2)                        as debe,
         f.importe_total                         as haber,
         f.created_at
    from public.facturas_proveedor f
   where f.estado <> 'anulada'
  union all
  select p.proveedor_id, p.fecha, 'pago'::text, p.id,
         coalesce(p.referencia, p.numero::text),
         p.importe_total, 0::numeric(14,2), p.created_at
    from public.pagos_proveedor p
   where p.estado <> 'anulado'
  union all
  select nc.proveedor_id, nc.fecha, 'nota_credito'::text, nc.id,
         concat_ws('-', nc.punto_venta, nc.numero),
         nc.importe, 0::numeric(14,2), nc.created_at
    from public.notas_credito_proveedor nc
   where nc.estado <> 'anulada'
)
select proveedor_id, fecha, tipo_movimiento, comprobante_id, comprobante, debe, haber,
       sum(haber - debe) over (
         partition by proveedor_id
         order by fecha, created_at
         rows between unbounded preceding and current row
       ) as saldo_acumulado
  from movimientos;


-- HU3: diferencias de precio y cantidad entre factura, OC y recepción.
-- Nota: detalle_recepcion usa costo_unitario (nombre heredado del Sprint 1).
create or replace view public.vw_conciliacion_factura as
select df.factura_id,
       f.proveedor_id,
       df.producto_id,
       doc.precio_unitario                       as precio_pactado,
       df.precio_unitario                        as precio_facturado,
       df.precio_unitario - doc.precio_unitario  as diferencia_precio,
       dr.cantidad                               as cantidad_recibida,
       df.cantidad                               as cantidad_facturada,
       df.cantidad - dr.cantidad                 as diferencia_cantidad
  from public.detalle_factura_proveedor df
  join public.facturas_proveedor f on f.id = df.factura_id
  left join public.detalle_recepcion dr on dr.id = df.detalle_recepcion_id
  left join public.detalle_orden_compra doc
         on doc.id = coalesce(df.detalle_orden_compra_id, dr.orden_compra_detalle_id);


-- HU11: sugerencias de reposición según stock mínimo.
create or replace view public.vw_sugerencias_reposicion as
select p.id     as producto_id,
       p.sku,
       p.nombre as producto,
       d.id     as deposito_id,
       d.nombre as deposito,
       coalesce(s.cantidad,0) - coalesce(s.comprometido,0) as stock_disponible,
       cs.min_stock,
       cs.max_stock,
       greatest(coalesce(cs.max_stock, cs.min_stock)
                - (coalesce(s.cantidad,0) - coalesce(s.comprometido,0)), 0) as cantidad_sugerida
  from public.configuracion_stock cs
  join public.productos p on p.id = cs.producto_id
  join public.depositos d on d.id = cs.deposito_id
  left join public.stock_x_deposito s
         on s.producto_id = cs.producto_id and s.deposito_id = cs.deposito_id
 where coalesce(s.cantidad,0) - coalesce(s.comprometido,0) < cs.min_stock;


-- ============================================================================
-- 9. DATOS INICIALES
-- ============================================================================

insert into public.tipos_movimiento (codigo, nombre)
select v.codigo, v.nombre
  from (values
    ('ING_RECEP',   'Ingreso por recepción de mercadería'),
    ('ANU_RECEP',   'Anulación de recepción'),
    ('EGR_DEVOL',   'Egreso por devolución a proveedor'),
    ('ING_REPOS',   'Ingreso por reposición de proveedor'),
    ('ING_DIRECTA', 'Ingreso por compra directa')
  ) as v(codigo, nombre)
 where not exists (select 1 from public.tipos_movimiento t where t.codigo = v.codigo);

insert into public.medios_pago (nombre)
select v.nombre
  from (values ('Efectivo'), ('Transferencia bancaria'), ('Cheque'),
               ('Cheque diferido'), ('Tarjeta de crédito'), ('Otro')) as v(nombre)
 where not exists (select 1 from public.medios_pago m where m.nombre = v.nombre);

insert into public.permisos (nombre)
select v.nombre
  from (values
    ('compras.solicitud.crear'), ('compras.solicitud.aprobar'),
    ('compras.orden.crear'), ('compras.orden.modificar'), ('compras.orden.cancelar'),
    ('compras.recepcion.registrar'), ('compras.recepcion.anular'),
    ('compras.devolucion.registrar'), ('compras.reportes.ver'),
    ('proveedores.alta'), ('proveedores.modificar'),
    ('proveedores.estado'), ('proveedores.consultar'),
    ('tesoreria.factura.registrar'), ('tesoreria.factura.anular'),
    ('tesoreria.nota_credito.registrar'),
    ('tesoreria.pago.registrar'), ('tesoreria.pago.anular'),
    ('tesoreria.cuenta_corriente.ver'),
    ('proveedores.rubros.gestionar')
  ) as v(nombre)
 where not exists (select 1 from public.permisos p where p.nombre = v.nombre);


-- ============================================================================
-- 10. ROW LEVEL SECURITY
-- ============================================================================
-- Criterio, alineado con el Sprint 1 (todas las tablas de stock ya tienen
-- rowsecurity = true):
--   · LECTURA: cualquier usuario autenticado. El sistema es interno y el
--     circuito lo exige (depósito lee órdenes de compra, compras lee
--     recepciones). Restringir lecturas por rol rompería el flujo.
--   · ESCRITURA: gobernada por usuario_permisos.
--   · anon: sin políticas, sin acceso.
-- Las tablas sin política de DELETE no admiten borrado por diseño: los
-- comprobantes se anulan, no se eliminan.

-- ----------------------------------------------------------------------------
-- 10.1 · DEPENDENCIA: función de permisos del Sprint 1
-- ----------------------------------------------------------------------------
-- Las políticas usan usuario_tiene_permiso(), la misma función que ya usan
-- Stock y Ajustes (definida en 0012). No se crea una función nueva a propósito:
-- duplicar la lógica haría que el bypass de admin por JWT valga en unos módulos
-- y en otros no.
do $$
begin
  if to_regprocedure('public.usuario_tiene_permiso(text)') is null then
    raise exception
      'Falta public.usuario_tiene_permiso(text), definida en 0012. Aplicá esa migración primero o ajustá la firma en esta.';
  end if;
end $$;


-- ----------------------------------------------------------------------------
-- 10.2 · HABILITAR RLS Y LECTURA PARA AUTENTICADOS
-- ----------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'rubros_proveedor','proveedores','proveedor_rubro','contactos_proveedor',
    'solicitudes_reposicion','detalle_solicitud_reposicion',
    'ordenes_compra','detalle_orden_compra',
    'devoluciones_proveedor','detalle_devolucion',
    'facturas_proveedor','detalle_factura_proveedor','factura_recepcion',
    'notas_credito_proveedor','medios_pago','pagos_proveedor','imputaciones'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "%s_select_autenticado" on public.%I', t, t);
    execute format(
      'create policy "%s_select_autenticado" on public.%I for select to authenticated using (true)',
      t, t);
  end loop;
end $$;


-- ----------------------------------------------------------------------------
-- 10.3 · POLÍTICAS DE ESCRITURA · PROVEEDORES
-- ----------------------------------------------------------------------------

drop policy if exists "proveedores_insert" on public.proveedores;
create policy "proveedores_insert" on public.proveedores
  for insert to authenticated
  with check (usuario_tiene_permiso('proveedores.alta'));

drop policy if exists "proveedores_update" on public.proveedores;
create policy "proveedores_update" on public.proveedores
  for update to authenticated
  using (usuario_tiene_permiso('proveedores.modificar') or usuario_tiene_permiso('proveedores.estado'))
  with check (usuario_tiene_permiso('proveedores.modificar') or usuario_tiene_permiso('proveedores.estado'));

drop policy if exists "rubros_insert" on public.rubros_proveedor;
create policy "rubros_insert" on public.rubros_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('proveedores.rubros.gestionar'));

drop policy if exists "rubros_update" on public.rubros_proveedor;
create policy "rubros_update" on public.rubros_proveedor
  for update to authenticated
  using (usuario_tiene_permiso('proveedores.rubros.gestionar'))
  with check (usuario_tiene_permiso('proveedores.rubros.gestionar'));

drop policy if exists "proveedor_rubro_insert" on public.proveedor_rubro;
create policy "proveedor_rubro_insert" on public.proveedor_rubro
  for insert to authenticated
  with check (usuario_tiene_permiso('proveedores.modificar'));

drop policy if exists "proveedor_rubro_delete" on public.proveedor_rubro;
create policy "proveedor_rubro_delete" on public.proveedor_rubro
  for delete to authenticated
  using (usuario_tiene_permiso('proveedores.modificar'));

drop policy if exists "contactos_insert" on public.contactos_proveedor;
create policy "contactos_insert" on public.contactos_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('proveedores.modificar'));

drop policy if exists "contactos_update" on public.contactos_proveedor;
create policy "contactos_update" on public.contactos_proveedor
  for update to authenticated
  using (usuario_tiene_permiso('proveedores.modificar'))
  with check (usuario_tiene_permiso('proveedores.modificar'));

drop policy if exists "contactos_delete" on public.contactos_proveedor;
create policy "contactos_delete" on public.contactos_proveedor
  for delete to authenticated
  using (usuario_tiene_permiso('proveedores.modificar'));


-- ----------------------------------------------------------------------------
-- 10.4 · POLÍTICAS DE ESCRITURA · COMPRAS
-- ----------------------------------------------------------------------------

drop policy if exists "solicitudes_insert" on public.solicitudes_reposicion;
create policy "solicitudes_insert" on public.solicitudes_reposicion
  for insert to authenticated
  with check (usuario_tiene_permiso('compras.solicitud.crear'));

-- Cubre tanto la edición del solicitante como la aprobación del encargado.
drop policy if exists "solicitudes_update" on public.solicitudes_reposicion;
create policy "solicitudes_update" on public.solicitudes_reposicion
  for update to authenticated
  using (usuario_tiene_permiso('compras.solicitud.crear') or usuario_tiene_permiso('compras.solicitud.aprobar'))
  with check (usuario_tiene_permiso('compras.solicitud.crear') or usuario_tiene_permiso('compras.solicitud.aprobar'));

drop policy if exists "det_solicitud_write" on public.detalle_solicitud_reposicion;
create policy "det_solicitud_write" on public.detalle_solicitud_reposicion
  for all to authenticated
  using (usuario_tiene_permiso('compras.solicitud.crear'))
  with check (usuario_tiene_permiso('compras.solicitud.crear'));

drop policy if exists "oc_insert" on public.ordenes_compra;
create policy "oc_insert" on public.ordenes_compra
  for insert to authenticated
  with check (usuario_tiene_permiso('compras.orden.crear'));

drop policy if exists "oc_update" on public.ordenes_compra;
-- Incluye 'compras.orden.crear' porque insertar una línea de detalle dispara
-- trg_recalcular_total_oc, que hace UPDATE sobre esta tabla y pasa por esta policy.
create policy "oc_update" on public.ordenes_compra
  for update to authenticated
  using (
    usuario_tiene_permiso('compras.orden.crear')
    or usuario_tiene_permiso('compras.orden.modificar')
    or usuario_tiene_permiso('compras.orden.cancelar')
  )
  with check (
    usuario_tiene_permiso('compras.orden.crear')
    or usuario_tiene_permiso('compras.orden.modificar')
    or usuario_tiene_permiso('compras.orden.cancelar')
  );

drop policy if exists "det_oc_write" on public.detalle_orden_compra;
create policy "det_oc_write" on public.detalle_orden_compra
  for all to authenticated
  using (usuario_tiene_permiso('compras.orden.crear') or usuario_tiene_permiso('compras.orden.modificar'))
  with check (usuario_tiene_permiso('compras.orden.crear') or usuario_tiene_permiso('compras.orden.modificar'));

drop policy if exists "devoluciones_insert" on public.devoluciones_proveedor;
create policy "devoluciones_insert" on public.devoluciones_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('compras.devolucion.registrar'));

drop policy if exists "devoluciones_update" on public.devoluciones_proveedor;
create policy "devoluciones_update" on public.devoluciones_proveedor
  for update to authenticated
  using (usuario_tiene_permiso('compras.devolucion.registrar'))
  with check (usuario_tiene_permiso('compras.devolucion.registrar'));

drop policy if exists "det_devolucion_write" on public.detalle_devolucion;
create policy "det_devolucion_write" on public.detalle_devolucion
  for all to authenticated
  using (usuario_tiene_permiso('compras.devolucion.registrar'))
  with check (usuario_tiene_permiso('compras.devolucion.registrar'));


-- ----------------------------------------------------------------------------
-- 10.5 · POLÍTICAS DE ESCRITURA · TESORERÍA
-- ----------------------------------------------------------------------------

drop policy if exists "facturas_insert" on public.facturas_proveedor;
create policy "facturas_insert" on public.facturas_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('tesoreria.factura.registrar'));

-- El UPDATE también lo dispara el trigger de imputaciones al recalcular saldos,
-- por eso incluye los permisos de pago y nota de crédito.
drop policy if exists "facturas_update" on public.facturas_proveedor;
create policy "facturas_update" on public.facturas_proveedor
  for update to authenticated
  using (
    usuario_tiene_permiso('tesoreria.factura.registrar')
    or usuario_tiene_permiso('tesoreria.factura.anular')
    or usuario_tiene_permiso('tesoreria.pago.registrar')
    or usuario_tiene_permiso('tesoreria.pago.anular')
    or usuario_tiene_permiso('tesoreria.nota_credito.registrar')
  )
  with check (
    usuario_tiene_permiso('tesoreria.factura.registrar')
    or usuario_tiene_permiso('tesoreria.factura.anular')
    or usuario_tiene_permiso('tesoreria.pago.registrar')
    or usuario_tiene_permiso('tesoreria.pago.anular')
    or usuario_tiene_permiso('tesoreria.nota_credito.registrar')
  );

drop policy if exists "det_factura_write" on public.detalle_factura_proveedor;
create policy "det_factura_write" on public.detalle_factura_proveedor
  for all to authenticated
  using (usuario_tiene_permiso('tesoreria.factura.registrar'))
  with check (usuario_tiene_permiso('tesoreria.factura.registrar'));

drop policy if exists "factura_recepcion_write" on public.factura_recepcion;
create policy "factura_recepcion_write" on public.factura_recepcion
  for all to authenticated
  using (usuario_tiene_permiso('tesoreria.factura.registrar'))
  with check (usuario_tiene_permiso('tesoreria.factura.registrar'));

drop policy if exists "nc_insert" on public.notas_credito_proveedor;
create policy "nc_insert" on public.notas_credito_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('tesoreria.nota_credito.registrar'));

drop policy if exists "nc_update" on public.notas_credito_proveedor;
create policy "nc_update" on public.notas_credito_proveedor
  for update to authenticated
  using (usuario_tiene_permiso('tesoreria.nota_credito.registrar'))
  with check (usuario_tiene_permiso('tesoreria.nota_credito.registrar'));

drop policy if exists "pagos_insert" on public.pagos_proveedor;
create policy "pagos_insert" on public.pagos_proveedor
  for insert to authenticated
  with check (usuario_tiene_permiso('tesoreria.pago.registrar'));

drop policy if exists "pagos_update" on public.pagos_proveedor;
create policy "pagos_update" on public.pagos_proveedor
  for update to authenticated
  using (usuario_tiene_permiso('tesoreria.pago.registrar') or usuario_tiene_permiso('tesoreria.pago.anular'))
  with check (usuario_tiene_permiso('tesoreria.pago.registrar') or usuario_tiene_permiso('tesoreria.pago.anular'));

drop policy if exists "imputaciones_write" on public.imputaciones;
-- El permiso exigido depende del origen real de la fila, no de "cualquiera de
-- los dos": así el error sale acá y no más adelante en el trigger.
create policy "imputaciones_write" on public.imputaciones
  for all to authenticated
  using (
    (pago_id is not null and (usuario_tiene_permiso('tesoreria.pago.registrar')
                              or usuario_tiene_permiso('tesoreria.pago.anular')))
    or
    (nota_credito_id is not null and usuario_tiene_permiso('tesoreria.nota_credito.registrar'))
  )
  with check (
    (pago_id is not null and usuario_tiene_permiso('tesoreria.pago.registrar'))
    or
    (nota_credito_id is not null and usuario_tiene_permiso('tesoreria.nota_credito.registrar'))
  );

-- medios_pago es un catálogo: se lee desde la app, se modifica por migración.
-- Sin políticas de escritura, nadie lo altera desde el cliente.

commit;