-- ============================================================================
-- 0031 · SPRINT 3: Base común — Clientes, Ventas y E-commerce
--
-- Única issue bloqueante del sprint (S3-00). Se apoya sobre el esquema de los
-- Sprints 1 y 2 ya existentes (productos, depositos, stock_x_deposito,
-- movimientos_stock, permisos, usuario_tiene_permiso, medios_pago). No los
-- recrea.
--
-- Esta migración deja las tablas, vistas y funciones compartidas que las
-- issues S3-01..S3-18 van a consumir con firma congelada. Varias funciones
-- tienen acá una versión "base" deliberadamente simple (ver comentarios en
-- la sección 8) que otra issue reemplaza después con `create or replace`
-- sin tocar la firma. Los triggers de negocio (historial de estados,
-- matrices de transición) NO van acá: cada issue dueña los agrega en su
-- propia migración sobre las tablas que esta migración ya deja creadas.
--
-- Convención de estados: igual que el resto del proyecto, en texto legible
-- ('Pendiente', 'Activo') y no en snake_case, porque así los citan las CA.
-- ============================================================================

begin;

-- ============================================================================
-- 1. USUARIOS INTERNOS
-- ============================================================================
-- Separa "quién puede loguearse" (auth.users, que también van a tener los
-- clientes web) de "quién es parte del equipo interno". La RLS de todo el
-- sistema pasa a depender de esto (sección 13).

create table if not exists public.usuarios_internos (
  usuario_id  uuid primary key references auth.users(id) on delete cascade,
  nombre      text not null,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.usuarios_internos enable row level security;

drop policy if exists "usuarios_internos_select_propio" on public.usuarios_internos;
create policy "usuarios_internos_select_propio" on public.usuarios_internos
  for select to authenticated
  using (usuario_id = auth.uid());

-- Se lee desde la app (ver quién es interno), se administra por migración.
-- Sin policy de insert/update/delete para 'authenticated' a propósito.

create or replace function public.es_usuario_interno()
returns boolean
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.usuarios_internos
    where usuario_id = auth.uid() and activo
  );
$$;

revoke all on function public.es_usuario_interno() from public;
grant execute on function public.es_usuario_interno() to authenticated;


-- ============================================================================
-- 2. CATÁLOGOS COMERCIALES
-- ============================================================================

create table if not exists public.listas_precio (
  id          uuid primary key default gen_random_uuid(),
  nombre      text not null,
  activo      boolean not null default true,
  created_at  timestamptz not null default now(),
  constraint uq_lista_precio_nombre unique (nombre),
  constraint chk_lista_precio_nombre_no_vacio check (length(btrim(nombre)) > 0)
);

create table if not exists public.condiciones_iva (
  id          uuid primary key default gen_random_uuid(),
  nombre      text not null,
  activo      boolean not null default true,
  created_at  timestamptz not null default now(),
  constraint uq_condicion_iva_nombre unique (nombre)
);

create table if not exists public.tipos_cliente (
  id                uuid primary key default gen_random_uuid(),
  nombre            text not null,
  lista_precio_id   uuid references public.listas_precio(id),
  activo            boolean not null default true,
  created_at        timestamptz not null default now(),
  constraint uq_tipo_cliente_nombre unique (nombre)
);


-- ============================================================================
-- 3. CLIENTES
-- ============================================================================

create table if not exists public.clientes (
  id                  uuid primary key default gen_random_uuid(),
  numero              bigint generated by default as identity,
  tipo_persona        text not null,
  nombre              text,
  apellido            text,
  razon_social        text,
  tipo_documento      text not null,
  numero_documento    text not null,
  condicion_iva_id    uuid not null references public.condiciones_iva(id),
  tipo_cliente_id     uuid not null references public.tipos_cliente(id),
  email               text,
  telefono            text not null,
  estado              text not null default 'Activo',
  origen              text not null default 'Mostrador',
  habilita_cta_cte    boolean not null default false,
  usuario_web_id      uuid references auth.users(id),
  created_by          uuid default auth.uid() references auth.users(id),
  updated_by          uuid references auth.users(id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint uq_cliente_numero unique (numero),
  constraint uq_cliente_documento unique (tipo_documento, numero_documento),
  constraint uq_cliente_usuario_web unique (usuario_web_id),
  constraint chk_cliente_tipo_persona check (tipo_persona in ('fisica','juridica')),
  constraint chk_cliente_tipo_documento check (tipo_documento in ('DNI','CUIT')),
  constraint chk_cliente_estado check (estado in ('Activo','Inactivo','Bloqueado')),
  constraint chk_cliente_origen check (origen in ('Mostrador','Web','Importación')),
  constraint chk_cliente_telefono_no_vacio check (length(btrim(telefono)) > 0),
  constraint chk_cliente_email check (email is null or email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  constraint chk_cliente_dni check (tipo_documento <> 'DNI' or numero_documento ~ '^[0-9]{7,8}$'),
  constraint chk_cliente_cuit check (tipo_documento <> 'CUIT' or numero_documento ~ '^[0-9]{11}$'),
  constraint chk_cliente_nombre check (
    (tipo_persona = 'fisica'
      and nombre is not null and length(btrim(nombre)) > 0
      and apellido is not null and length(btrim(apellido)) > 0
      and razon_social is null)
    or
    (tipo_persona = 'juridica'
      and razon_social is not null and length(btrim(razon_social)) > 0
      and nombre is null and apellido is null)
  )
);

drop trigger if exists trg_clientes_updated_at on public.clientes;
create trigger trg_clientes_updated_at
  before update on public.clientes
  for each row execute function public.fn_set_updated_at();

-- Un cliente web tiene permiso de UPDATE sobre su propia fila (CA-05 de
-- S3-15: "editar teléfono y domicilios"), pero la policy de RLS no puede
-- restringir columnas por sí sola. Este trigger cierra ese hueco: si quien
-- actualiza no es interno, solo puede tocar `telefono` y `email`.
create or replace function public.fn_restringir_update_cliente_web()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if public.es_usuario_interno() then
    return new;
  end if;

  if new.usuario_web_id is distinct from old.usuario_web_id
     or new.numero is distinct from old.numero
     or new.tipo_persona is distinct from old.tipo_persona
     or new.nombre is distinct from old.nombre
     or new.apellido is distinct from old.apellido
     or new.razon_social is distinct from old.razon_social
     or new.tipo_documento is distinct from old.tipo_documento
     or new.numero_documento is distinct from old.numero_documento
     or new.condicion_iva_id is distinct from old.condicion_iva_id
     or new.tipo_cliente_id is distinct from old.tipo_cliente_id
     or new.estado is distinct from old.estado
     or new.origen is distinct from old.origen
     or new.habilita_cta_cte is distinct from old.habilita_cta_cte
  then
    raise exception 'Un cliente web solo puede modificar su teléfono y su email'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_clientes_restringir_update_web on public.clientes;
create trigger trg_clientes_restringir_update_web
  before update on public.clientes
  for each row execute function public.fn_restringir_update_cliente_web();

create table if not exists public.historial_estado_cliente (
  id                uuid primary key default gen_random_uuid(),
  cliente_id        uuid not null references public.clientes(id) on delete cascade,
  estado_anterior   text,
  estado_nuevo      text not null,
  motivo            text,
  usuario_id        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now()
);

create table if not exists public.domicilios_cliente (
  id            uuid primary key default gen_random_uuid(),
  cliente_id    uuid not null references public.clientes(id) on delete cascade,
  alias         text not null,
  calle         text not null,
  numero        text not null,
  localidad     text not null,
  provincia     text not null,
  codigo_postal text,
  referencias   text,
  es_principal  boolean not null default false,
  activo        boolean not null default true,
  created_at    timestamptz not null default now(),
  constraint chk_domicilio_alias_no_vacio check (length(btrim(alias)) > 0)
);

create unique index if not exists ux_domicilio_alias_activo
  on public.domicilios_cliente (cliente_id, alias)
  where activo;

create unique index if not exists ux_domicilio_principal
  on public.domicilios_cliente (cliente_id)
  where es_principal and activo;


-- ============================================================================
-- 4. VENTAS · catálogos y parametría
-- ============================================================================

create table if not exists public.precios_lista (
  id                uuid primary key default gen_random_uuid(),
  lista_precio_id   uuid not null references public.listas_precio(id) on delete cascade,
  producto_id       uuid not null references public.productos(id),
  precio            numeric(14,2) not null,
  created_at        timestamptz not null default now(),
  constraint uq_precio_lista_producto unique (lista_precio_id, producto_id),
  constraint chk_precio_lista_positivo check (precio > 0)
);

create table if not exists public.reglas_descuento (
  id                uuid primary key default gen_random_uuid(),
  tipo_aplicacion   text not null,
  referencia_id     uuid not null,
  porcentaje        numeric(5,2) not null,
  activo            boolean not null default true,
  created_at        timestamptz not null default now(),
  constraint chk_regla_descuento_tipo check (tipo_aplicacion in ('tipo_cliente','categoria','producto')),
  constraint chk_regla_descuento_porcentaje check (porcentaje between 0.01 and 100)
);

create table if not exists public.parametros_ventas (
  id      uuid primary key default gen_random_uuid(),
  clave   text not null,
  valor   jsonb not null,
  constraint uq_parametro_venta_clave unique (clave)
);

create table if not exists public.autorizaciones_descuento (
  id                uuid primary key default gen_random_uuid(),
  porcentaje        numeric(5,2) not null,
  autorizado_por    uuid not null references auth.users(id),
  created_at        timestamptz not null default now(),
  expira_at         timestamptz not null default (now() + interval '5 minutes'),
  constraint chk_autorizacion_porcentaje check (porcentaje between 0.01 and 100)
);

create table if not exists public.puntos_venta (
  id      uuid primary key default gen_random_uuid(),
  numero  text not null,
  nombre  text not null,
  activo  boolean not null default true,
  constraint uq_punto_venta_numero unique (numero)
);

create table if not exists public.numeracion_comprobantes (
  punto_venta_id    uuid not null references public.puntos_venta(id),
  tipo_comprobante  text not null,
  letra             text not null,
  ultimo_numero     bigint not null default 0,
  primary key (punto_venta_id, tipo_comprobante, letra)
);


-- ============================================================================
-- 5. VENTAS · operación
-- ============================================================================

create table if not exists public.ventas (
  id              uuid primary key default gen_random_uuid(),
  numero          bigint generated by default as identity,
  deposito_id     uuid not null references public.depositos(id),
  cliente_id      uuid not null references public.clientes(id),
  vendedor_id     uuid not null default auth.uid() references auth.users(id),
  estado          text not null default 'Pendiente',
  total           numeric(14,2) not null default 0,
  observaciones   text,
  created_at      timestamptz not null default now(),
  constraint uq_venta_numero unique (numero),
  constraint chk_venta_estado check (estado in ('Pendiente','Facturada','Entregada','Anulada'))
);

create table if not exists public.detalle_venta (
  id                        uuid primary key default gen_random_uuid(),
  venta_id                  uuid not null references public.ventas(id) on delete cascade,
  producto_id               uuid not null references public.productos(id),
  cantidad                  numeric not null,
  cantidad_backorder        numeric not null default 0,
  precio_unitario           numeric(14,2) not null,
  descuento_pct             numeric(5,2) not null default 0,
  autorizacion_descuento_id uuid references public.autorizaciones_descuento(id),
  subtotal                  numeric(14,2) generated always as
                               (cantidad * precio_unitario * (1 - descuento_pct / 100.0)) stored,
  created_at                timestamptz not null default now(),
  constraint uq_detalle_venta_producto unique (venta_id, producto_id),
  constraint chk_detalle_venta_cantidad check (cantidad > 0),
  constraint chk_detalle_venta_backorder check (cantidad_backorder >= 0),
  constraint chk_detalle_venta_precio check (precio_unitario > 0),
  constraint chk_detalle_venta_descuento check (descuento_pct >= 0 and descuento_pct <= 100)
);

create table if not exists public.historial_estado_venta (
  id                uuid primary key default gen_random_uuid(),
  venta_id          uuid not null references public.ventas(id) on delete cascade,
  estado_anterior   text,
  estado_nuevo      text not null,
  motivo            text,
  usuario_id        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now()
);

create table if not exists public.comprobantes_venta (
  id                      uuid primary key default gen_random_uuid(),
  venta_id                uuid not null references public.ventas(id),
  tipo_comprobante        text not null,
  letra                   text not null,
  punto_venta_id          uuid not null references public.puntos_venta(id),
  numero                  bigint not null,
  comprobante_asociado_id uuid references public.comprobantes_venta(id),
  fecha_emision           timestamptz not null default now(),
  neto                    numeric(14,2) not null,
  iva                     numeric(14,2) not null,
  total                   numeric(14,2) not null,
  cae                     text,
  cae_vencimiento         date,
  estado                  text not null default 'Emitido',
  created_by              uuid default auth.uid() references auth.users(id),
  created_at              timestamptz not null default now(),
  constraint uq_comprobante_venta_numero unique (punto_venta_id, tipo_comprobante, letra, numero),
  constraint chk_comprobante_tipo check (tipo_comprobante in ('factura','nota_credito','nota_debito')),
  constraint chk_comprobante_letra check (letra in ('A','B','C')),
  constraint chk_comprobante_estado check (estado in ('Emitido','Anulado')),
  constraint chk_comprobante_total check (total > 0)
);

create table if not exists public.cobros_venta (
  id          uuid primary key default gen_random_uuid(),
  venta_id    uuid not null references public.ventas(id),
  numero      bigint generated by default as identity,
  total       numeric(14,2) not null,
  created_by  uuid default auth.uid() references auth.users(id),
  created_at  timestamptz not null default now(),
  constraint uq_cobro_numero unique (numero),
  constraint chk_cobro_total check (total > 0)
);

create table if not exists public.detalle_cobro (
  id                uuid primary key default gen_random_uuid(),
  cobro_id          uuid not null references public.cobros_venta(id) on delete cascade,
  medio_pago_id     uuid not null references public.medios_pago(id),
  monto             numeric(14,2) not null,
  monto_recibido    numeric(14,2),
  vuelto            numeric(14,2) not null default 0,
  referencia        text,
  created_at        timestamptz not null default now(),
  constraint chk_detalle_cobro_monto check (monto > 0)
);


-- ============================================================================
-- 6. E-COMMERCE
-- ============================================================================

create table if not exists public.carritos (
  id          uuid primary key default gen_random_uuid(),
  cliente_id  uuid not null references public.clientes(id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint uq_carrito_cliente unique (cliente_id)
);

drop trigger if exists trg_carritos_updated_at on public.carritos;
create trigger trg_carritos_updated_at
  before update on public.carritos
  for each row execute function public.fn_set_updated_at();

create table if not exists public.items_carrito (
  id            uuid primary key default gen_random_uuid(),
  carrito_id    uuid not null references public.carritos(id) on delete cascade,
  producto_id   uuid not null references public.productos(id),
  cantidad      numeric not null,
  created_at    timestamptz not null default now(),
  constraint uq_item_carrito_producto unique (carrito_id, producto_id),
  constraint chk_item_carrito_cantidad check (cantidad > 0)
);

create table if not exists public.pedidos_web (
  id                uuid primary key default gen_random_uuid(),
  numero            bigint generated by default as identity,
  cliente_id        uuid not null references public.clientes(id),
  deposito_id       uuid not null references public.depositos(id),
  tipo_entrega      text not null,
  domicilio_id      uuid references public.domicilios_cliente(id),
  estado            text not null default 'Pendiente de pago',
  total             numeric(14,2) not null,
  referencia_pago   text,
  created_at        timestamptz not null default now(),
  constraint uq_pedido_web_numero unique (numero),
  constraint chk_pedido_web_tipo_entrega check (tipo_entrega in ('retiro','envio')),
  constraint chk_pedido_web_estado check (estado in (
    'Pendiente de pago','Pagado','En preparación','Listo para retirar',
    'Enviado','Entregado','Cancelado'
  ))
);

create table if not exists public.detalle_pedido_web (
  id                uuid primary key default gen_random_uuid(),
  pedido_id         uuid not null references public.pedidos_web(id) on delete cascade,
  producto_id       uuid not null references public.productos(id),
  cantidad          numeric not null,
  precio_unitario   numeric(14,2) not null,
  subtotal          numeric(14,2) generated always as (cantidad * precio_unitario) stored,
  constraint chk_detalle_pedido_web_cantidad check (cantidad > 0),
  constraint chk_detalle_pedido_web_precio check (precio_unitario > 0)
);

create table if not exists public.historial_estado_pedido (
  id                uuid primary key default gen_random_uuid(),
  pedido_id         uuid not null references public.pedidos_web(id) on delete cascade,
  estado_anterior   text,
  estado_nuevo      text not null,
  motivo            text,
  usuario_id        uuid default auth.uid() references auth.users(id),
  created_at        timestamptz not null default now()
);


-- ============================================================================
-- 7. AJUSTES SOBRE TABLAS EXISTENTES
-- ============================================================================

alter table public.productos
  add column if not exists imagen_url      text,
  add column if not exists publicado_web   boolean not null default false;

insert into public.medios_pago (nombre)
select v.nombre
  from (values ('Tarjeta de débito'), ('Cuenta corriente'), ('Mercado Pago')) as v(nombre)
 where not exists (select 1 from public.medios_pago m where m.nombre = v.nombre);


-- ============================================================================
-- 8. FUNCIONES COMPARTIDAS · firmas congeladas
-- ============================================================================
-- Todas quedan documentadas acá con parámetros y retorno (DoD). Las marcadas
-- "versión base" las reemplaza otra issue con `create or replace`, sin tocar
-- la firma ni el nombre.

-- cliente_habilitado_para_vender(uuid) — versión base: solo mira el estado.
-- La reemplaza S3-02 sin cambiar la firma.
--
-- @param p_cliente uuid del cliente.
-- @returns boolean true si el cliente puede operar en una venta.
create or replace function public.cliente_habilitado_para_vender(p_cliente uuid)
returns boolean
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select coalesce(
    (select estado = 'Activo' from public.clientes where id = p_cliente),
    false
  );
$$;

revoke all on function public.cliente_habilitado_para_vender(uuid) from public;
grant execute on function public.cliente_habilitado_para_vender(uuid) to authenticated;


-- calcular_precio_venta(producto, cliente, cantidad) — versión base: precio
-- de la lista asignada al tipo de cliente, o la lista "General" si el
-- cliente es nulo o su tipo no tiene lista asignada. `p_cantidad` está en la
-- firma para que S3-06 pueda agregar descuentos por volumen sin romper a
-- quien ya la llama.
--
-- @param p_producto uuid del producto.
-- @param p_cliente uuid del cliente, o null.
-- @param p_cantidad cantidad de la línea (no usada en la versión base).
-- @returns numeric precio unitario, o null si no hay precio cargado.
create or replace function public.calcular_precio_venta(
  p_producto uuid,
  p_cliente uuid,
  p_cantidad numeric default 1
)
returns numeric
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
  v_lista uuid;
  v_precio numeric;
begin
  if p_cliente is not null then
    select tc.lista_precio_id into v_lista
    from public.clientes c
    join public.tipos_cliente tc on tc.id = c.tipo_cliente_id
    where c.id = p_cliente;
  end if;

  if v_lista is null then
    select id into v_lista
    from public.listas_precio
    where nombre = 'General' and activo;
  end if;

  select precio into v_precio
  from public.precios_lista
  where lista_precio_id = v_lista
    and producto_id = p_producto;

  return v_precio;
end;
$$;

revoke all on function public.calcular_precio_venta(uuid, uuid, numeric) from public;
grant execute on function public.calcular_precio_venta(uuid, uuid, numeric) to authenticated;


-- validar_descuento_manual(porcentaje) — versión base: nunca requiere
-- autorización. La reemplaza S3-06, que lo compara contra
-- parametros_ventas.limite_descuento_manual.
--
-- @param p_porcentaje numeric porcentaje de descuento manual solicitado.
-- @returns jsonb {requiere_autorizacion: boolean, limite: numeric|null}.
create or replace function public.validar_descuento_manual(p_porcentaje numeric)
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select jsonb_build_object('requiere_autorizacion', false, 'limite', null::numeric);
$$;

revoke all on function public.validar_descuento_manual(numeric) from public;
grant execute on function public.validar_descuento_manual(numeric) to authenticated;


-- autorizar_descuento(porcentaje) — versión base: autoriza siempre (no
-- valida permiso). La reemplaza S3-06, que exige 'ventas.descuento.autorizar'.
-- Corre con el token del supervisor (auth.uid() = supervisor), no con el del
-- vendedor que abrió el modal.
--
-- @param p_porcentaje numeric porcentaje a autorizar.
-- @returns uuid id de la autorización creada (válida 5 minutos).
create or replace function public.autorizar_descuento(p_porcentaje numeric)
returns uuid
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_id uuid;
begin
  insert into public.autorizaciones_descuento (porcentaje, autorizado_por)
  values (p_porcentaje, auth.uid())
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.autorizar_descuento(numeric) from public;
grant execute on function public.autorizar_descuento(numeric) to authenticated;


-- autorizacion_descuento_valida(id, porcentaje) — vigente mientras no haya
-- expirado y cubra el porcentaje solicitado.
--
-- @param p_id uuid id de la autorización.
-- @param p_porcentaje numeric porcentaje que se pretende aplicar.
-- @returns boolean true si la autorización es válida para ese porcentaje.
create or replace function public.autorizacion_descuento_valida(p_id uuid, p_porcentaje numeric)
returns boolean
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.autorizaciones_descuento
    where id = p_id
      and porcentaje >= p_porcentaje
      and expira_at > now()
  );
$$;

revoke all on function public.autorizacion_descuento_valida(uuid, numeric) from public;
grant execute on function public.autorizacion_descuento_valida(uuid, numeric) to authenticated;


-- comprometer_stock(deposito, items) — aumenta stock_x_deposito.comprometido
-- para cada ítem, sin tocar la cantidad física. Todo o nada: si algún ítem no
-- tiene disponible suficiente, levanta P0001/STOCK_INSUFICIENTE con producto,
-- disponible y solicitado, y no compromete nada (la excepción revierte la
-- transacción completa del llamador). SECURITY DEFINER porque la usan tanto
-- flujos internos (ventas) como el checkout web, que no tiene permiso directo
-- de escritura sobre stock_x_deposito.
--
-- @param p_deposito uuid depósito donde se compromete.
-- @param p_items jsonb array de {producto_id, cantidad}.
-- @returns void
create or replace function public.comprometer_stock(p_deposito uuid, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item record;
  v_disponible numeric;
begin
  if p_deposito is null then
    raise exception 'El depósito es obligatorio';
  end if;

  for v_item in
    select (elem->>'producto_id')::uuid as producto_id,
           (elem->>'cantidad')::numeric as cantidad
    from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as elem
  loop
    if v_item.producto_id is null or v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'Cada ítem necesita producto_id y una cantidad mayor a 0';
    end if;

    select s.cantidad - s.comprometido into v_disponible
    from public.stock_x_deposito s
    where s.producto_id = v_item.producto_id
      and s.deposito_id = p_deposito
    for update;

    if not found or v_disponible < v_item.cantidad then
      raise exception 'STOCK_INSUFICIENTE: producto % — disponible % — solicitado %',
        v_item.producto_id, coalesce(v_disponible, 0), v_item.cantidad
        using errcode = 'P0001';
    end if;

    update public.stock_x_deposito
    set comprometido = comprometido + v_item.cantidad,
        updated_at = now()
    where producto_id = v_item.producto_id
      and deposito_id = p_deposito;
  end loop;
end;
$$;

revoke all on function public.comprometer_stock(uuid, jsonb) from public;
grant execute on function public.comprometer_stock(uuid, jsonb) to authenticated;


-- liberar_stock(deposito, items) — inversa de comprometer_stock: resta de
-- comprometido sin tocar la cantidad física (venta anulada, pedido cancelado).
--
-- @param p_deposito uuid depósito donde se libera.
-- @param p_items jsonb array de {producto_id, cantidad}.
-- @returns void
create or replace function public.liberar_stock(p_deposito uuid, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item record;
begin
  if p_deposito is null then
    raise exception 'El depósito es obligatorio';
  end if;

  for v_item in
    select (elem->>'producto_id')::uuid as producto_id,
           (elem->>'cantidad')::numeric as cantidad
    from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as elem
  loop
    if v_item.producto_id is null or v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'Cada ítem necesita producto_id y una cantidad mayor a 0';
    end if;

    update public.stock_x_deposito
    set comprometido = comprometido - v_item.cantidad,
        updated_at = now()
    where producto_id = v_item.producto_id
      and deposito_id = p_deposito;
  end loop;
end;
$$;

revoke all on function public.liberar_stock(uuid, jsonb) from public;
grant execute on function public.liberar_stock(uuid, jsonb) to authenticated;


-- egresar_comprometido(deposito, items) — venta entregada: descuenta la
-- cantidad física Y el comprometido, y deja un movimiento de stock trazable
-- (tipo 'egreso', ya existente desde el Sprint 1) para no perder auditoría.
--
-- @param p_deposito uuid depósito de origen del egreso.
-- @param p_items jsonb array de {producto_id, cantidad}.
-- @returns void
create or replace function public.egresar_comprometido(p_deposito uuid, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item record;
  v_tipo_id uuid;
  v_movimiento_id uuid;
begin
  if p_deposito is null then
    raise exception 'El depósito es obligatorio';
  end if;

  select id into v_tipo_id from public.tipos_movimiento where codigo = 'egreso';
  if v_tipo_id is null then
    raise exception 'No existe el tipo de movimiento "egreso"';
  end if;

  insert into public.movimientos_stock (
    tipo_movimiento_id, deposito_origen_id, estado_movimiento, observaciones
  )
  values (v_tipo_id, p_deposito, 'confirmado', 'Egreso por venta entregada')
  returning id into v_movimiento_id;

  for v_item in
    select (elem->>'producto_id')::uuid as producto_id,
           (elem->>'cantidad')::numeric as cantidad
    from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as elem
  loop
    if v_item.producto_id is null or v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'Cada ítem necesita producto_id y una cantidad mayor a 0';
    end if;

    update public.stock_x_deposito
    set cantidad = cantidad - v_item.cantidad,
        comprometido = comprometido - v_item.cantidad,
        updated_at = now()
    where producto_id = v_item.producto_id
      and deposito_id = p_deposito;

    insert into public.detalle_movimiento (movimiento_id, producto_id, cantidad)
    values (v_movimiento_id, v_item.producto_id, v_item.cantidad);
  end loop;
end;
$$;

revoke all on function public.egresar_comprometido(uuid, jsonb) from public;
grant execute on function public.egresar_comprometido(uuid, jsonb) to authenticated;


-- siguiente_numero_comprobante(punto_venta, tipo, letra) — numeración
-- correlativa sin saltos por punto de venta/tipo/letra. Transaccional: si el
-- llamador aborta después, el incremento se revierte con el resto (no es una
-- SEQUENCE de Postgres, que nunca hace rollback).
--
-- @param p_punto_venta uuid.
-- @param p_tipo text tipo de comprobante ('factura'|'nota_credito'|'nota_debito').
-- @param p_letra text letra ('A'|'B'|'C').
-- @returns bigint próximo número a usar.
create or replace function public.siguiente_numero_comprobante(
  p_punto_venta uuid,
  p_tipo text,
  p_letra text
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_numero bigint;
begin
  insert into public.numeracion_comprobantes (punto_venta_id, tipo_comprobante, letra, ultimo_numero)
  values (p_punto_venta, p_tipo, p_letra, 1)
  on conflict (punto_venta_id, tipo_comprobante, letra)
  do update set ultimo_numero = public.numeracion_comprobantes.ultimo_numero + 1
  returning ultimo_numero into v_numero;

  return v_numero;
end;
$$;

revoke all on function public.siguiente_numero_comprobante(uuid, text, text) from public;
grant execute on function public.siguiente_numero_comprobante(uuid, text, text) to authenticated;


-- ============================================================================
-- 9. VISTAS
-- ============================================================================

create or replace view public.v_stock_disponible as
select
  s.producto_id,
  s.deposito_id,
  s.cantidad,
  s.comprometido,
  s.cantidad - s.comprometido as disponible
from public.stock_x_deposito s;

grant select on public.v_stock_disponible to authenticated;

-- Sin cantidades exactas (CA-01 de S3-14): solo "Disponible"/"Sin stock".
-- El precio es el de la lista General.
create or replace view public.v_catalogo_web as
select
  p.id,
  p.sku,
  p.nombre,
  p.descripcion,
  p.imagen_url,
  p.categoria_id,
  p.marca_id,
  pl.precio as precio,
  coalesce(sum(greatest(sd.cantidad - sd.comprometido, 0)), 0) > 0 as disponible
from public.productos p
left join public.precios_lista pl
  on pl.producto_id = p.id
 and pl.lista_precio_id = (select id from public.listas_precio where nombre = 'General')
left join public.stock_x_deposito sd
  on sd.producto_id = p.id
where p.estado_producto = 'activo'
  and p.publicado_web
group by p.id, p.sku, p.nombre, p.descripcion, p.imagen_url, p.categoria_id, p.marca_id, pl.precio;

grant select on public.v_catalogo_web to anon, authenticated;


-- ============================================================================
-- 10. ÍNDICES
-- ============================================================================

create index if not exists ix_clientes_estado             on public.clientes (estado);
create index if not exists ix_clientes_documento           on public.clientes (numero_documento);
create index if not exists ix_clientes_nombre_trgm         on public.clientes using gin (to_tsvector('spanish', coalesce(nombre,'') || ' ' || coalesce(apellido,'') || ' ' || coalesce(razon_social,'')));
create index if not exists ix_domicilios_cliente           on public.domicilios_cliente (cliente_id);
create index if not exists ix_historial_estado_cliente     on public.historial_estado_cliente (cliente_id);

create index if not exists ix_precios_lista_lista          on public.precios_lista (lista_precio_id);
create index if not exists ix_precios_lista_producto       on public.precios_lista (producto_id);

create index if not exists ix_ventas_estado                on public.ventas (estado);
create index if not exists ix_ventas_cliente                on public.ventas (cliente_id);
create index if not exists ix_ventas_deposito               on public.ventas (deposito_id);
create index if not exists ix_detalle_venta_venta           on public.detalle_venta (venta_id);
create index if not exists ix_historial_estado_venta        on public.historial_estado_venta (venta_id);
create index if not exists ix_comprobantes_venta_venta      on public.comprobantes_venta (venta_id);
create index if not exists ix_cobros_venta_venta            on public.cobros_venta (venta_id);
create index if not exists ix_detalle_cobro_cobro           on public.detalle_cobro (cobro_id);

create index if not exists ix_carritos_cliente              on public.carritos (cliente_id);
create index if not exists ix_items_carrito_carrito         on public.items_carrito (carrito_id);
create index if not exists ix_pedidos_web_cliente           on public.pedidos_web (cliente_id);
create index if not exists ix_pedidos_web_estado            on public.pedidos_web (estado);
create index if not exists ix_detalle_pedido_web_pedido     on public.detalle_pedido_web (pedido_id);
create index if not exists ix_historial_estado_pedido       on public.historial_estado_pedido (pedido_id);


-- ============================================================================
-- 11. PERMISOS NUEVOS
-- ============================================================================

insert into public.permisos (nombre)
select v.nombre
  from (values
    ('clientes.alta'), ('clientes.modificar'), ('clientes.estado'), ('clientes.importar'),
    ('ventas.registrar'), ('ventas.cobrar'), ('ventas.facturar'), ('ventas.anular'), ('ventas.entregar'),
    ('ventas.descuento.autorizar'),
    ('precios.gestionar'),
    ('ecommerce.publicar'), ('ecommerce.pedidos.gestionar')
  ) as v(nombre)
 where not exists (select 1 from public.permisos p where p.nombre = v.nombre);


-- ============================================================================
-- 12. STORAGE
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

drop policy if exists "productos_bucket_lectura_publica" on storage.objects;
create policy "productos_bucket_lectura_publica" on storage.objects
  for select
  using (bucket_id = 'productos');

drop policy if exists "productos_bucket_escritura_interna" on storage.objects;
create policy "productos_bucket_escritura_interna" on storage.objects
  for all to authenticated
  using (bucket_id = 'productos' and public.usuario_tiene_permiso('ecommerce.publicar'))
  with check (bucket_id = 'productos' and public.usuario_tiene_permiso('ecommerce.publicar'));


-- ============================================================================
-- 13. ROW LEVEL SECURITY
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 13.1 · Migrar las políticas viejas "using (true)" de Stock/Proveedores/
--        Compras/Tesorería a "using (es_usuario_interno())". Cubre también
--        el "with check" cuando la policy es de escritura (FOR ALL), para
--        que un cliente web autenticado no pueda insertar filas ahí.
-- ----------------------------------------------------------------------------

do $$
declare
  r record;
begin
  for r in
    select tablename, policyname, with_check
    from pg_policies
    where schemaname = 'public'
      and qual = 'true'
  loop
    if r.with_check is not null then
      execute format(
        'alter policy %I on public.%I using (public.es_usuario_interno()) with check (public.es_usuario_interno())',
        r.policyname, r.tablename
      );
    else
      execute format(
        'alter policy %I on public.%I using (public.es_usuario_interno())',
        r.policyname, r.tablename
      );
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 13.2 · Habilitar RLS + lectura interna en todas las tablas nuevas
-- ----------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'condiciones_iva','tipos_cliente','clientes','historial_estado_cliente','domicilios_cliente',
    'listas_precio','precios_lista','reglas_descuento','parametros_ventas','autorizaciones_descuento',
    'puntos_venta','numeracion_comprobantes',
    'ventas','detalle_venta','historial_estado_venta','comprobantes_venta','cobros_venta','detalle_cobro',
    'carritos','items_carrito','pedidos_web','detalle_pedido_web','historial_estado_pedido'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "%s_select_interno" on public.%I', t, t);
    execute format(
      'create policy "%s_select_interno" on public.%I for select to authenticated using (public.es_usuario_interno())',
      t, t);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 13.3 · Escritura · Clientes
-- ----------------------------------------------------------------------------

-- El cliente web necesita leer su propia fila (ClienteWebContext, Mis
-- datos); la policy "clientes_select_interno" de 13.2 no lo cubre porque
-- filtra por es_usuario_interno().
drop policy if exists "clientes_select_propio" on public.clientes;
create policy "clientes_select_propio" on public.clientes
  for select to authenticated
  using (usuario_web_id = auth.uid());

drop policy if exists "clientes_insert" on public.clientes;
create policy "clientes_insert" on public.clientes
  for insert to authenticated
  with check (public.usuario_tiene_permiso('clientes.alta') or public.usuario_tiene_permiso('clientes.importar'));

drop policy if exists "clientes_update" on public.clientes;
create policy "clientes_update" on public.clientes
  for update to authenticated
  using (
    public.usuario_tiene_permiso('clientes.modificar')
    or public.usuario_tiene_permiso('clientes.estado')
    or usuario_web_id = auth.uid()
  )
  with check (
    public.usuario_tiene_permiso('clientes.modificar')
    or public.usuario_tiene_permiso('clientes.estado')
    or usuario_web_id = auth.uid()
  );

drop policy if exists "historial_estado_cliente_insert" on public.historial_estado_cliente;
create policy "historial_estado_cliente_insert" on public.historial_estado_cliente
  for insert to authenticated
  with check (public.es_usuario_interno());

drop policy if exists "domicilios_cliente_write" on public.domicilios_cliente;
create policy "domicilios_cliente_write" on public.domicilios_cliente
  for all to authenticated
  using (
    public.es_usuario_interno()
    or cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  )
  with check (
    public.es_usuario_interno()
    or cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  );

-- ----------------------------------------------------------------------------
-- 13.4 · Escritura · Ventas
-- ----------------------------------------------------------------------------

drop policy if exists "listas_precio_write" on public.listas_precio;
create policy "listas_precio_write" on public.listas_precio
  for all to authenticated
  using (public.usuario_tiene_permiso('precios.gestionar'))
  with check (public.usuario_tiene_permiso('precios.gestionar'));

drop policy if exists "precios_lista_write" on public.precios_lista;
create policy "precios_lista_write" on public.precios_lista
  for all to authenticated
  using (public.usuario_tiene_permiso('precios.gestionar'))
  with check (public.usuario_tiene_permiso('precios.gestionar'));

drop policy if exists "reglas_descuento_write" on public.reglas_descuento;
create policy "reglas_descuento_write" on public.reglas_descuento
  for all to authenticated
  using (public.usuario_tiene_permiso('precios.gestionar'))
  with check (public.usuario_tiene_permiso('precios.gestionar'));

drop policy if exists "parametros_ventas_write" on public.parametros_ventas;
create policy "parametros_ventas_write" on public.parametros_ventas
  for all to authenticated
  using (public.usuario_tiene_permiso('precios.gestionar'))
  with check (public.usuario_tiene_permiso('precios.gestionar'));

-- Base: cualquier interno autoriza (autorizar_descuento "autoriza siempre").
-- S3-06 puede endurecerlo agregando el chequeo de permiso adentro de la
-- función sin tener que tocar esta policy.
drop policy if exists "autorizaciones_descuento_insert" on public.autorizaciones_descuento;
create policy "autorizaciones_descuento_insert" on public.autorizaciones_descuento
  for insert to authenticated
  with check (public.es_usuario_interno());

drop policy if exists "puntos_venta_write" on public.puntos_venta;
create policy "puntos_venta_write" on public.puntos_venta
  for all to authenticated
  using (public.es_usuario_interno())
  with check (public.es_usuario_interno());

drop policy if exists "numeracion_comprobantes_write" on public.numeracion_comprobantes;
create policy "numeracion_comprobantes_write" on public.numeracion_comprobantes
  for all to authenticated
  using (public.es_usuario_interno())
  with check (public.es_usuario_interno());

drop policy if exists "ventas_insert" on public.ventas;
create policy "ventas_insert" on public.ventas
  for insert to authenticated
  with check (public.usuario_tiene_permiso('ventas.registrar'));

drop policy if exists "ventas_update" on public.ventas;
create policy "ventas_update" on public.ventas
  for update to authenticated
  using (
    public.usuario_tiene_permiso('ventas.registrar')
    or public.usuario_tiene_permiso('ventas.anular')
    or public.usuario_tiene_permiso('ventas.entregar')
    or public.usuario_tiene_permiso('ventas.facturar')
    or public.usuario_tiene_permiso('ventas.cobrar')
  )
  with check (
    public.usuario_tiene_permiso('ventas.registrar')
    or public.usuario_tiene_permiso('ventas.anular')
    or public.usuario_tiene_permiso('ventas.entregar')
    or public.usuario_tiene_permiso('ventas.facturar')
    or public.usuario_tiene_permiso('ventas.cobrar')
  );

drop policy if exists "detalle_venta_write" on public.detalle_venta;
create policy "detalle_venta_write" on public.detalle_venta
  for all to authenticated
  using (public.usuario_tiene_permiso('ventas.registrar'))
  with check (public.usuario_tiene_permiso('ventas.registrar'));

drop policy if exists "historial_estado_venta_insert" on public.historial_estado_venta;
create policy "historial_estado_venta_insert" on public.historial_estado_venta
  for insert to authenticated
  with check (public.es_usuario_interno());

drop policy if exists "comprobantes_venta_write" on public.comprobantes_venta;
create policy "comprobantes_venta_write" on public.comprobantes_venta
  for all to authenticated
  using (public.usuario_tiene_permiso('ventas.facturar') or public.usuario_tiene_permiso('ventas.anular'))
  with check (public.usuario_tiene_permiso('ventas.facturar') or public.usuario_tiene_permiso('ventas.anular'));

drop policy if exists "cobros_venta_write" on public.cobros_venta;
create policy "cobros_venta_write" on public.cobros_venta
  for all to authenticated
  using (public.usuario_tiene_permiso('ventas.cobrar'))
  with check (public.usuario_tiene_permiso('ventas.cobrar'));

drop policy if exists "detalle_cobro_write" on public.detalle_cobro;
create policy "detalle_cobro_write" on public.detalle_cobro
  for all to authenticated
  using (public.usuario_tiene_permiso('ventas.cobrar'))
  with check (public.usuario_tiene_permiso('ventas.cobrar'));

-- ----------------------------------------------------------------------------
-- 13.5 · Escritura · E-commerce (interno + cliente web dueño de sus filas)
-- ----------------------------------------------------------------------------

drop policy if exists "carritos_cliente_web" on public.carritos;
create policy "carritos_cliente_web" on public.carritos
  for all to authenticated
  using (cliente_id in (select id from public.clientes where usuario_web_id = auth.uid()))
  with check (cliente_id in (select id from public.clientes where usuario_web_id = auth.uid()));

drop policy if exists "items_carrito_cliente_web" on public.items_carrito;
create policy "items_carrito_cliente_web" on public.items_carrito
  for all to authenticated
  using (carrito_id in (
    select id from public.carritos
    where cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  ))
  with check (carrito_id in (
    select id from public.carritos
    where cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  ));

drop policy if exists "pedidos_web_select_propio" on public.pedidos_web;
create policy "pedidos_web_select_propio" on public.pedidos_web
  for select to authenticated
  using (cliente_id in (select id from public.clientes where usuario_web_id = auth.uid()));

drop policy if exists "pedidos_web_insert_propio" on public.pedidos_web;
create policy "pedidos_web_insert_propio" on public.pedidos_web
  for insert to authenticated
  with check (cliente_id in (select id from public.clientes where usuario_web_id = auth.uid()));

drop policy if exists "pedidos_web_update_interno" on public.pedidos_web;
create policy "pedidos_web_update_interno" on public.pedidos_web
  for update to authenticated
  using (public.usuario_tiene_permiso('ecommerce.pedidos.gestionar'))
  with check (public.usuario_tiene_permiso('ecommerce.pedidos.gestionar'));

drop policy if exists "detalle_pedido_web_select_propio" on public.detalle_pedido_web;
create policy "detalle_pedido_web_select_propio" on public.detalle_pedido_web
  for select to authenticated
  using (pedido_id in (
    select id from public.pedidos_web
    where cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  ));

drop policy if exists "detalle_pedido_web_insert_propio" on public.detalle_pedido_web;
create policy "detalle_pedido_web_insert_propio" on public.detalle_pedido_web
  for insert to authenticated
  with check (pedido_id in (
    select id from public.pedidos_web
    where cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  ));

drop policy if exists "historial_estado_pedido_select_propio" on public.historial_estado_pedido;
create policy "historial_estado_pedido_select_propio" on public.historial_estado_pedido
  for select to authenticated
  using (pedido_id in (
    select id from public.pedidos_web
    where cliente_id in (select id from public.clientes where usuario_web_id = auth.uid())
  ));

drop policy if exists "historial_estado_pedido_insert" on public.historial_estado_pedido;
create policy "historial_estado_pedido_insert" on public.historial_estado_pedido
  for insert to authenticated
  with check (public.es_usuario_interno());


-- ============================================================================
-- 14. DATOS DE PRUEBA (seed)
-- ============================================================================

-- 14.1 · Usuarios internos.
-- Completá el resto del equipo con su email real de Supabase Auth antes de
-- aplicar en un ambiente compartido (ver README). Solo se inserta lo que
-- matchea contra auth.users, así que si un email no existe todavía esta
-- sentencia no hace nada (no falla). Sanz, Trogliero y Serrano todavía no
-- tienen usuario creado en el proyecto de staging al momento de escribir
-- esto: agregalos acá apenas lo tengan.
insert into public.usuarios_internos (usuario_id, nombre)
select u.id, x.nombre
from (values
  ('admin@gmail.com', 'Lucas Cenzano'),
  ('gonzavillalba123@gmail.com', 'Gonzalo Villalba'),
  ('mateoquartin@gmail.com', 'Mateo Quartin'),
  ('nicosalasfarjat123@gmail.com', 'Nicolás Salas Farjat')
  -- ,('EMAIL_REAL_AQUI', 'Facundo Sanz')
  -- ,('EMAIL_REAL_AQUI', 'Tomás Trogliero')
  -- ,('EMAIL_REAL_AQUI', 'Carmela Serrano')
) as x(email, nombre)
join auth.users u on u.email = x.email
where not exists (
  select 1 from public.usuarios_internos ui where ui.usuario_id = u.id
);

-- 14.2 · Catálogos comerciales.
insert into public.condiciones_iva (nombre)
select v.nombre from (values
  ('Responsable Inscripto'), ('Monotributo'), ('Consumidor Final'), ('Exento')
) as v(nombre)
where not exists (select 1 from public.condiciones_iva c where c.nombre = v.nombre);

insert into public.listas_precio (nombre)
select v.nombre from (values ('General'), ('Mayorista')) as v(nombre)
where not exists (select 1 from public.listas_precio l where l.nombre = v.nombre);

insert into public.tipos_cliente (nombre, lista_precio_id)
select 'Consumidor Final', (select id from public.listas_precio where nombre = 'General')
where not exists (select 1 from public.tipos_cliente where nombre = 'Consumidor Final');

insert into public.tipos_cliente (nombre, lista_precio_id)
select 'Empresa constructora', (select id from public.listas_precio where nombre = 'Mayorista')
where not exists (select 1 from public.tipos_cliente where nombre = 'Empresa constructora');

insert into public.tipos_cliente (nombre, lista_precio_id)
select 'Consumidor web', (select id from public.listas_precio where nombre = 'General')
where not exists (select 1 from public.tipos_cliente where nombre = 'Consumidor web');

-- Precio para todos los productos activos, en ambas listas (CA-06).
insert into public.precios_lista (lista_precio_id, producto_id, precio)
select lp.id, p.id, 1000
from public.listas_precio lp
cross join public.productos p
where p.estado_producto = 'activo'
  and not exists (
    select 1 from public.precios_lista pl
    where pl.lista_precio_id = lp.id and pl.producto_id = p.id
  );

insert into public.puntos_venta (numero, nombre)
select '0001', 'Casa Central'
where not exists (select 1 from public.puntos_venta where numero = '0001');

-- 14.3 · Clientes (5), con casos de prueba citados por S3-01/04/15.
insert into public.clientes (
  tipo_persona, razon_social, tipo_documento, numero_documento,
  condicion_iva_id, tipo_cliente_id, email, telefono, habilita_cta_cte
)
select 'juridica', 'Constructora Andes SRL', 'CUIT', '20123456786',
  (select id from public.condiciones_iva where nombre = 'Responsable Inscripto'),
  (select id from public.tipos_cliente where nombre = 'Empresa constructora'),
  'compras@andes.com.ar', '3874000001', true
where not exists (select 1 from public.clientes where numero_documento = '20123456786');

insert into public.clientes (
  tipo_persona, nombre, apellido, tipo_documento, numero_documento,
  condicion_iva_id, tipo_cliente_id, email, telefono
)
select 'fisica', 'Juan', 'Pérez', 'DNI', '30111222',
  (select id from public.condiciones_iva where nombre = 'Consumidor Final'),
  (select id from public.tipos_cliente where nombre = 'Consumidor Final'),
  'juan.perez@example.com', '3874000002'
where not exists (select 1 from public.clientes where numero_documento = '30111222');

insert into public.clientes (
  tipo_persona, nombre, apellido, tipo_documento, numero_documento,
  condicion_iva_id, tipo_cliente_id, email, telefono
)
select 'fisica', 'María', 'Gómez', 'DNI', '28555444',
  (select id from public.condiciones_iva where nombre = 'Monotributo'),
  (select id from public.tipos_cliente where nombre = 'Consumidor Final'),
  'maria.gomez@example.com', '3874000003'
where not exists (select 1 from public.clientes where numero_documento = '28555444');

insert into public.clientes (
  tipo_persona, nombre, apellido, tipo_documento, numero_documento,
  condicion_iva_id, tipo_cliente_id, email, telefono
)
select 'fisica', 'Carlos', 'Ibáñez', 'DNI', '33222111',
  (select id from public.condiciones_iva where nombre = 'Exento'),
  (select id from public.tipos_cliente where nombre = 'Consumidor Final'),
  'carlos.ibanez@example.com', '3874000004'
where not exists (select 1 from public.clientes where numero_documento = '33222111');

insert into public.clientes (
  tipo_persona, razon_social, tipo_documento, numero_documento,
  condicion_iva_id, tipo_cliente_id, email, telefono, habilita_cta_cte
)
select 'juridica', 'Ferretería Sur SA', 'CUIT', '30712345671',
  (select id from public.condiciones_iva where nombre = 'Responsable Inscripto'),
  (select id from public.tipos_cliente where nombre = 'Empresa constructora'),
  'compras@ferreteriasur.com.ar', '3874000005', false
where not exists (select 1 from public.clientes where numero_documento = '30712345671');

-- Domicilio para Juan Pérez, usado por los pedidos web de prueba.
insert into public.domicilios_cliente (cliente_id, alias, calle, numero, localidad, provincia, es_principal)
select c.id, 'Casa', 'Belgrano', '450', 'Salta', 'Salta', true
from public.clientes c
where c.numero_documento = '30111222'
  and not exists (select 1 from public.domicilios_cliente d where d.cliente_id = c.id);

-- 14.4 · Ventas: 3 Pendientes + 1 Facturada con comprobante y cobro (CA-06).
-- Se omite si todavía no hay depósito o producto activo cargado.
do $$
declare
  v_deposito_id     uuid;
  v_producto_id     uuid;
  v_precio          numeric;
  v_cliente_ri      uuid;
  v_cliente_cf      uuid;
  v_punto_venta_id  uuid;
  v_medio_efectivo  uuid;
  v_venta_id        uuid;
  v_numero          bigint;
  v_comprobante_id  uuid;
  v_vendedor_id     uuid;
  i                 int;
begin
  select id into v_deposito_id from public.depositos order by created_at limit 1;
  select id into v_producto_id from public.productos where estado_producto = 'activo' order by created_at limit 1;
  select id into v_cliente_ri from public.clientes where numero_documento = '20123456786';
  select id into v_cliente_cf from public.clientes where numero_documento = '30111222';
  select id into v_punto_venta_id from public.puntos_venta where numero = '0001';
  select id into v_medio_efectivo from public.medios_pago where nombre = 'Efectivo';

  -- auth.uid() da null acá: el SQL Editor corre como postgres, sin JWT.
  -- vendedor_id es NOT NULL, así que hace falta un usuario real explícito.
  select usuario_id into v_vendedor_id from public.usuarios_internos limit 1;
  if v_vendedor_id is null then
    select id into v_vendedor_id from auth.users limit 1;
  end if;

  if v_deposito_id is null or v_producto_id is null or v_cliente_ri is null
     or v_cliente_cf is null or v_vendedor_id is null then
    raise notice 'Seed de ventas omitido: falta depósito, producto activo, cliente base o usuario.';
    return;
  end if;

  if exists (select 1 from public.ventas) then
    raise notice 'Seed de ventas omitido: ya hay ventas cargadas.';
    return;
  end if;

  select coalesce(precio, 1000) into v_precio
  from public.precios_lista pl
  join public.listas_precio lp on lp.id = pl.lista_precio_id
  where lp.nombre = 'General' and pl.producto_id = v_producto_id;

  -- 3 ventas Pendientes.
  for i in 1..3 loop
    insert into public.ventas (deposito_id, cliente_id, vendedor_id, estado, total)
    values (v_deposito_id, v_cliente_cf, v_vendedor_id, 'Pendiente', v_precio * 2)
    returning id into v_venta_id;

    insert into public.detalle_venta (venta_id, producto_id, cantidad, precio_unitario)
    values (v_venta_id, v_producto_id, 2, v_precio);
  end loop;

  -- 1 venta Facturada con comprobante y cobro.
  insert into public.ventas (deposito_id, cliente_id, vendedor_id, estado, total)
  values (v_deposito_id, v_cliente_ri, v_vendedor_id, 'Facturada', v_precio * 5)
  returning id into v_venta_id;

  insert into public.detalle_venta (venta_id, producto_id, cantidad, precio_unitario)
  values (v_venta_id, v_producto_id, 5, v_precio);

  v_numero := public.siguiente_numero_comprobante(v_punto_venta_id, 'factura', 'A');

  insert into public.comprobantes_venta (
    venta_id, tipo_comprobante, letra, punto_venta_id, numero,
    neto, iva, total, cae, cae_vencimiento
  )
  values (
    v_venta_id, 'factura', 'A', v_punto_venta_id, v_numero,
    round(v_precio * 5 / 1.21, 2), round(v_precio * 5 - v_precio * 5 / 1.21, 2), v_precio * 5,
    'HOMOLOGACIÓN', current_date + 10
  )
  returning id into v_comprobante_id;

  insert into public.cobros_venta (venta_id, total)
  values (v_venta_id, v_precio * 5)
  returning id into v_comprobante_id;

  insert into public.detalle_cobro (cobro_id, medio_pago_id, monto)
  values (v_comprobante_id, v_medio_efectivo, v_precio * 5);
end $$;

-- 14.5 · Pedidos web: 2 (uno Pendiente de pago, uno Pagado — CA-06 / S3-16).
do $$
declare
  v_deposito_id   uuid;
  v_producto_id   uuid;
  v_precio        numeric;
  v_cliente_id    uuid;
  v_domicilio_id  uuid;
  v_pedido_id     uuid;
begin
  select id into v_deposito_id from public.depositos order by created_at limit 1;
  select id into v_producto_id from public.productos where estado_producto = 'activo' order by created_at limit 1;
  select id into v_cliente_id from public.clientes where numero_documento = '30111222';
  select id into v_domicilio_id from public.domicilios_cliente where cliente_id = v_cliente_id limit 1;

  if v_deposito_id is null or v_producto_id is null or v_cliente_id is null then
    raise notice 'Seed de pedidos web omitido: falta depósito, producto activo o cliente base.';
    return;
  end if;

  if exists (select 1 from public.pedidos_web) then
    raise notice 'Seed de pedidos web omitido: ya hay pedidos cargados.';
    return;
  end if;

  select coalesce(precio, 1000) into v_precio
  from public.precios_lista pl
  join public.listas_precio lp on lp.id = pl.lista_precio_id
  where lp.nombre = 'General' and pl.producto_id = v_producto_id;

  insert into public.pedidos_web (cliente_id, deposito_id, tipo_entrega, domicilio_id, estado, total)
  values (v_cliente_id, v_deposito_id, 'envio', v_domicilio_id, 'Pendiente de pago', v_precio * 3)
  returning id into v_pedido_id;

  insert into public.detalle_pedido_web (pedido_id, producto_id, cantidad, precio_unitario)
  values (v_pedido_id, v_producto_id, 3, v_precio);

  insert into public.pedidos_web (cliente_id, deposito_id, tipo_entrega, estado, total, referencia_pago)
  values (v_cliente_id, v_deposito_id, 'retiro', 'Pagado', v_precio * 1, 'HOMOLOGACIÓN-0001')
  returning id into v_pedido_id;

  insert into public.detalle_pedido_web (pedido_id, producto_id, cantidad, precio_unitario)
  values (v_pedido_id, v_producto_id, 1, v_precio);
end $$;

commit;
