-- ============================================================================
-- 0061 · Cuenta Corriente de Clientes, Límite de Crédito y Recibos de Cobranza
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1. EXTENSIÓN DE TABLA CLIENTES
-- ----------------------------------------------------------------------------
alter table public.clientes
  add column if not exists limite_credito numeric(14,2) not null default 0 check (limite_credito >= 0),
  add column if not exists plazo_credito_dias integer not null default 30 check (plazo_credito_dias >= 0);

-- ----------------------------------------------------------------------------
-- 2. TABLAS DE RECIBOS DE COBRANZA E IMPUTACIÓN
-- ----------------------------------------------------------------------------
create table if not exists public.recibos_cobranza_cliente (
  id             uuid primary key default gen_random_uuid(),
  numero         bigint generated by default as identity,
  cliente_id     uuid not null references public.clientes(id) on delete restrict,
  fecha          date not null default current_date,
  total          numeric(14,2) not null check (total > 0),
  observaciones  text,
  estado         text not null default 'emitido' check (estado in ('emitido', 'anulado')),
  created_by     uuid default auth.uid() references auth.users(id),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.detalle_medio_recibo (
  id              uuid primary key default gen_random_uuid(),
  recibo_id       uuid not null references public.recibos_cobranza_cliente(id) on delete cascade,
  medio_pago_id   uuid not null references public.medios_pago(id) on delete restrict,
  monto           numeric(14,2) not null check (monto > 0),
  monto_recibido  numeric(14,2),
  referencia      text,
  created_at      timestamptz not null default now()
);

create table if not exists public.imputacion_recibo_venta (
  id              uuid primary key default gen_random_uuid(),
  recibo_id       uuid not null references public.recibos_cobranza_cliente(id) on delete cascade,
  venta_id        uuid not null references public.ventas(id) on delete restrict,
  monto_imputado  numeric(14,2) not null check (monto_imputado > 0),
  created_at      timestamptz not null default now()
);

create index if not exists idx_recibos_cliente_fecha on public.recibos_cobranza_cliente(cliente_id, fecha);
create index if not exists idx_imputacion_venta on public.imputacion_recibo_venta(venta_id);

-- ----------------------------------------------------------------------------
-- 3. VISTA DEL LIBRO MAYOR DE CUENTA CORRIENTE DE CLIENTES
-- ----------------------------------------------------------------------------
-- Criterio contable: El cliente es un crédito por ventas (activo para el corralón).
-- Facturas/ventas a crédito van al DEBE (aumentan la deuda del cliente).
-- Recibos de cobro y Notas de crédito van al HABER (disminuyen la deuda).
-- Saldo acumulado = sum(debe - haber). Positivo = deudor.
create or replace view public.vw_cuenta_corriente_cliente as
with movimientos as (
  -- 1) Ventas a Cuenta Corriente (Debe)
  select v.cliente_id,
         coalesce(comp.fecha_emision, v.created_at::date) as fecha,
         'factura'::text as tipo_movimiento,
         v.id as comprobante_id,
         case
           when comp.id is not null then concat_ws('-', comp.letra, lpad((select pv.numero from public.puntos_venta pv where pv.id = comp.punto_venta_id), 4, '0'), lpad(comp.numero::text, 8, '0'))
           else concat('Venta #', v.numero)
         end as comprobante,
         concat('Venta #', v.numero) as referencia,
         dc.monto as debe,
         0::numeric(14,2) as haber,
         v.created_at
    from public.ventas v
    join public.cobros_venta cv on cv.venta_id = v.id
    join public.detalle_cobro dc on dc.cobro_id = cv.id
    join public.medios_pago mp on mp.id = dc.medio_pago_id and lower(mp.nombre) = 'cuenta corriente'
    left join public.comprobantes_venta comp on comp.venta_id = v.id and comp.tipo_comprobante = 'factura' and comp.estado <> 'Anulado'
   where v.estado <> 'Anulada'

  union all

  -- 2) Recibos de Cobranza (Haber)
  select r.cliente_id,
         r.fecha as fecha,
         'recibo'::text as tipo_movimiento,
         r.id as comprobante_id,
         concat('Recibo #', r.numero) as comprobante,
         coalesce(r.observaciones, 'Cobranza en cuenta corriente') as referencia,
         0::numeric(14,2) as debe,
         r.total as haber,
         r.created_at
    from public.recibos_cobranza_cliente r
   where r.estado <> 'anulado'

  union all

  -- 3) Notas de Crédito de ventas a Cuenta Corriente (Haber)
  -- Una NC total anula la venta (fn_anular_venta_por_nota_credito) y la venta
  -- anulada ya no suma en el DEBE: su NC tampoco cuenta, o el cliente quedaría
  -- con saldo a favor por el total. Si la venta se cobró en parte con otros
  -- medios, la NC acredita como máximo lo que se financió en cuenta corriente.
  select v.cliente_id,
         nc.fecha_emision as fecha,
         'nota_credito'::text as tipo_movimiento,
         nc.id as comprobante_id,
         concat_ws('-', nc.letra, lpad((select pv.numero from public.puntos_venta pv where pv.id = nc.punto_venta_id), 4, '0'), lpad(nc.numero::text, 8, '0')) as comprobante,
         concat('NC s/ Venta #', v.numero) as referencia,
         0::numeric(14,2) as debe,
         least(nc.total, dc.monto) as haber,
         nc.created_at
    from public.comprobantes_venta nc
    join public.ventas v on v.id = nc.venta_id
    join public.cobros_venta cv on cv.venta_id = v.id
    join public.detalle_cobro dc on dc.cobro_id = cv.id
    join public.medios_pago mp on mp.id = dc.medio_pago_id and lower(mp.nombre) = 'cuenta corriente'
   where nc.tipo_comprobante = 'nota_credito'
     and nc.estado <> 'Anulado'
     and v.estado <> 'Anulada'
)
select m.cliente_id,
       m.fecha,
       m.tipo_movimiento,
       m.comprobante_id,
       m.comprobante,
       m.referencia,
       m.debe,
       m.haber,
       sum(m.debe - m.haber) over (
         partition by m.cliente_id
         order by m.fecha, m.created_at, m.comprobante_id
         rows between unbounded preceding and current row
       ) as saldo_acumulado,
       m.created_at
  from movimientos m;

-- La vista aplica la RLS de quien consulta (como v_stock_disponible en 0034):
-- solo el personal interno ve ventas y cobros. Sin esto correría con los
-- permisos del dueño y cualquier usuario logueado vería todas las cuentas.
alter view public.vw_cuenta_corriente_cliente set (security_invoker = true);

-- ----------------------------------------------------------------------------
-- 4. FUNCIONES DE CÁLCULO DE SALDO Y ESTADO DE CRÉDITO
-- ----------------------------------------------------------------------------
create or replace function public.fn_saldo_cta_cte_cliente(p_cliente_id uuid)
returns numeric(14,2)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_saldo numeric(14,2);
begin
  select coalesce(sum(debe - haber), 0)
    into v_saldo
    from public.vw_cuenta_corriente_cliente
   where cliente_id = p_cliente_id;
  return coalesce(v_saldo, 0);
end;
$$;

create or replace function public.obtener_resumen_cta_cte_cliente(p_cliente_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_cliente record;
  v_saldo numeric(14,2);
  v_disponible numeric(14,2);
  v_pendientes_count integer;
begin
  -- SECURITY DEFINER: sin este control cualquier usuario logueado (incluido
  -- un cliente web) podría consultar el crédito de otro cliente.
  if not public.es_usuario_interno() then
    raise exception 'No tenés permiso para consultar cuentas corrientes' using errcode = '42501';
  end if;

  select c.id, c.habilita_cta_cte, c.limite_credito, c.plazo_credito_dias
    into v_cliente
    from public.clientes c
   where c.id = p_cliente_id;

  if not found then
    raise exception 'Cliente no encontrado' using errcode = '42501';
  end if;

  v_saldo := public.fn_saldo_cta_cte_cliente(p_cliente_id);

  if v_cliente.limite_credito > 0 then
    v_disponible := greatest(0::numeric(14,2), v_cliente.limite_credito - v_saldo);
  else
    v_disponible := 0::numeric(14,2);
  end if;

  select count(distinct v.id)
    into v_pendientes_count
    from public.ventas v
    join public.cobros_venta cv on cv.venta_id = v.id
    join public.detalle_cobro dc on dc.cobro_id = cv.id
    join public.medios_pago mp on mp.id = dc.medio_pago_id and lower(mp.nombre) = 'cuenta corriente'
   where v.cliente_id = p_cliente_id
     and v.estado <> 'Anulada'
     and dc.monto > coalesce((
       select sum(irv.monto_imputado)
         from public.imputacion_recibo_venta irv
        where irv.venta_id = v.id
     ), 0);

  return jsonb_build_object(
    'cliente_id', v_cliente.id,
    'habilita_cta_cte', v_cliente.habilita_cta_cte,
    'limite_credito', v_cliente.limite_credito,
    'plazo_credito_dias', v_cliente.plazo_credito_dias,
    'saldo_deudor', v_saldo,
    'credito_disponible', v_disponible,
    'facturas_pendientes_count', v_pendientes_count
  );
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. LISTAR VENTAS PENDIENTES DE CANCELACIÓN EN CTA CTE
-- ----------------------------------------------------------------------------
create or replace function public.listar_ventas_pendientes_cta_cte(p_cliente_id uuid)
returns table (
  venta_id uuid,
  numero bigint,
  fecha timestamptz,
  comprobante text,
  total_credito numeric,
  total_imputado numeric,
  saldo_pendiente numeric
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.es_usuario_interno() then
    raise exception 'No tenés permiso para consultar cuentas corrientes' using errcode = '42501';
  end if;

  return query
  select v.id as venta_id,
         v.numero,
         v.created_at as fecha,
         case
           when comp.id is not null then concat_ws('-', comp.letra, lpad((select pv.numero from public.puntos_venta pv where pv.id = comp.punto_venta_id), 4, '0'), lpad(comp.numero::text, 8, '0'))
           else concat('Venta #', v.numero)
         end as comprobante,
         dc.monto as total_credito,
         coalesce(imp.imputado, 0)::numeric as total_imputado,
         (dc.monto - coalesce(imp.imputado, 0))::numeric as saldo_pendiente
    from public.ventas v
    join public.cobros_venta cv on cv.venta_id = v.id
    join public.detalle_cobro dc on dc.cobro_id = cv.id
    join public.medios_pago mp on mp.id = dc.medio_pago_id and lower(mp.nombre) = 'cuenta corriente'
    left join public.comprobantes_venta comp on comp.venta_id = v.id and comp.tipo_comprobante = 'factura' and comp.estado <> 'Anulado'
    left join (
      select irv.venta_id, sum(irv.monto_imputado) as imputado
        from public.imputacion_recibo_venta irv
       group by irv.venta_id
    ) imp on imp.venta_id = v.id
   where v.cliente_id = p_cliente_id
     and v.estado <> 'Anulada'
     and (dc.monto - coalesce(imp.imputado, 0)) > 0
   order by v.created_at asc;
end;
$$;

-- ----------------------------------------------------------------------------
-- 6. REGISTRAR RECIBO DE COBRANZA CON IMPUTACIÓN
-- ----------------------------------------------------------------------------
create or replace function public.registrar_recibo_cobranza(
  p_cliente_id uuid,
  p_fecha date,
  p_medios jsonb,
  p_imputaciones jsonb default '[]'::jsonb,
  p_observaciones text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_usuario uuid := auth.uid();
  v_cliente record;
  v_total_medios numeric(14,2) := 0;
  v_total_imputado numeric(14,2) := 0;
  v_recibo record;
  v_item jsonb;
  v_medio_id uuid;
  v_monto numeric(14,2);
  v_ref text;
  v_venta_id uuid;
  v_monto_imp numeric(14,2);
  v_saldo_venta numeric(14,2);
begin
  -- Mismo permiso que el cobro en mostrador (registrar_cobro).
  if v_usuario is null or not public.usuario_tiene_permiso('ventas.cobrar') then
    raise exception 'No tiene permiso para registrar cobros en cuenta corriente' using errcode = '42501';
  end if;

  select id, nombre, apellido, razon_social, estado
    into v_cliente
    from public.clientes
   where id = p_cliente_id
   for update;

  if not found then
    raise exception 'Cliente no encontrado' using errcode = '22023';
  end if;

  if v_cliente.estado <> 'Activo' then
    raise exception 'El cliente no se encuentra activo' using errcode = '22023';
  end if;

  if p_medios is null or jsonb_typeof(p_medios) <> 'array' or jsonb_array_length(p_medios) = 0 then
    raise exception 'Debe especificar al menos un medio de cobro' using errcode = '22023';
  end if;

  -- 1) Calcular y validar medios de pago
  for v_item in select value from jsonb_array_elements(p_medios)
  loop
    v_medio_id := nullif(btrim(v_item ->> 'medio_pago_id'), '')::uuid;
    v_monto := nullif(btrim(v_item ->> 'monto'), '')::numeric(14,2);

    if v_medio_id is null or v_monto is null or v_monto <= 0 then
      raise exception 'Cada medio de cobro debe tener un medio válido y un importe mayor a cero' using errcode = '22023';
    end if;

    if not exists (select 1 from public.medios_pago where id = v_medio_id and activo = true) then
      raise exception 'Medio de pago inexistente o inactivo' using errcode = '22023';
    end if;

    v_total_medios := v_total_medios + v_monto;
  end loop;

  -- 2) Validar imputaciones si fueron provistas
  -- Una venta por imputación: cada línea se compara contra el saldo pendiente,
  -- así que dos líneas a la misma venta podrían imputar más de lo adeudado.
  if p_imputaciones is not null and jsonb_typeof(p_imputaciones) = 'array' and exists (
    select 1
      from jsonb_array_elements(p_imputaciones) as elem
     where nullif(btrim(elem ->> 'venta_id'), '') is not null
     group by elem ->> 'venta_id'
    having count(*) > 1
  ) then
    raise exception 'Hay ventas repetidas en las imputaciones: unificá el monto en una sola línea' using errcode = '22023';
  end if;

  if p_imputaciones is not null and jsonb_typeof(p_imputaciones) = 'array' then
    for v_item in select value from jsonb_array_elements(p_imputaciones)
    loop
      v_venta_id := nullif(btrim(v_item ->> 'venta_id'), '')::uuid;
      v_monto_imp := nullif(btrim(v_item ->> 'monto_imputado'), '')::numeric(14,2);

      if v_venta_id is null or v_monto_imp is null or v_monto_imp <= 0 then
        raise exception 'Cada imputación debe tener una venta válida y un monto mayor a cero' using errcode = '22023';
      end if;

      -- Verificar que la venta corresponda a este cliente y sea de cta cte
      select (dc.monto - coalesce((select sum(irv.monto_imputado) from public.imputacion_recibo_venta irv where irv.venta_id = v.id), 0))
        into v_saldo_venta
        from public.ventas v
        join public.cobros_venta cv on cv.venta_id = v.id
        join public.detalle_cobro dc on dc.cobro_id = cv.id
        join public.medios_pago mp on mp.id = dc.medio_pago_id and lower(mp.nombre) = 'cuenta corriente'
       where v.id = v_venta_id and v.cliente_id = p_cliente_id;

      if not found then
        raise exception 'La venta % no es una deuda válida en cuenta corriente del cliente', v_venta_id using errcode = '22023';
      end if;

      if v_monto_imp > v_saldo_venta then
        raise exception 'El monto imputado (%) supera el saldo pendiente de la venta (%)', v_monto_imp, v_saldo_venta using errcode = '22023';
      end if;

      v_total_imputado := v_total_imputado + v_monto_imp;
    end loop;

    if v_total_imputado > v_total_medios then
      raise exception 'El total imputado (%) no puede ser mayor al total cobrado (%)', v_total_imputado, v_total_medios using errcode = '22023';
    end if;
  end if;

  -- 3) Insertar Cabecera de Recibo
  insert into public.recibos_cobranza_cliente (
    cliente_id, fecha, total, observaciones, created_by
  ) values (
    p_cliente_id, coalesce(p_fecha, current_date), v_total_medios, nullif(trim(p_observaciones), ''), v_usuario
  ) returning * into v_recibo;

  -- 4) Insertar Detalle de Medios
  for v_item in select value from jsonb_array_elements(p_medios)
  loop
    v_medio_id := (v_item ->> 'medio_pago_id')::uuid;
    v_monto := (v_item ->> 'monto')::numeric(14,2);
    v_ref := nullif(trim(v_item ->> 'referencia'), '');

    insert into public.detalle_medio_recibo (
      recibo_id, medio_pago_id, monto, referencia
    ) values (
      v_recibo.id, v_medio_id, v_monto, v_ref
    );
  end loop;

  -- 5) Insertar Imputaciones
  if p_imputaciones is not null and jsonb_typeof(p_imputaciones) = 'array' then
    for v_item in select value from jsonb_array_elements(p_imputaciones)
    loop
      v_venta_id := (v_item ->> 'venta_id')::uuid;
      v_monto_imp := (v_item ->> 'monto_imputado')::numeric(14,2);

      insert into public.imputacion_recibo_venta (
        recibo_id, venta_id, monto_imputado
      ) values (
        v_recibo.id, v_venta_id, v_monto_imp
      );
    end loop;
  end if;

  return jsonb_build_object(
    'id', v_recibo.id,
    'numero', v_recibo.numero,
    'total', v_recibo.total,
    'fecha', v_recibo.fecha,
    'cliente_id', v_recibo.cliente_id,
    'total_imputado', v_total_imputado,
    'saldo_a_cuenta', (v_total_medios - v_total_imputado)
  );
end;
$$;

-- ----------------------------------------------------------------------------
-- 7. REFORZAR registrar_cobro CON VALIDACIÓN DE LÍMITE DE CRÉDITO
-- ----------------------------------------------------------------------------
create or replace function public.registrar_cobro(
  p_venta uuid,
  p_detalle jsonb
)
returns table (
  venta_id uuid,
  cobro_id uuid,
  numero bigint,
  total numeric,
  fecha timestamptz,
  created_by uuid,
  cobrada boolean,
  estado_venta text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_usuario uuid := auth.uid();
  v_total_venta numeric(14,2);
  v_estado_venta text;
  v_cliente_cta_cte boolean;
  v_cliente_limite numeric(14,2);
  v_cliente_id uuid;
  v_saldo_actual numeric(14,2);
  v_item jsonb;
  v_medio_id uuid;
  v_medio_nombre text;
  v_monto numeric(14,2);
  v_monto_recibido numeric(14,2);
  v_vuelto numeric(14,2);
  v_referencia text;
  v_total_aplicado numeric(14,2) := 0;
  v_cobro_id uuid;
  v_cobro_numero bigint;
  v_cobro_fecha timestamptz;
begin
  -- Igual que 0041: cobrar exige el permiso granular, no alcanza con ser interno.
  if v_usuario is null or not public.usuario_tiene_permiso('ventas.cobrar') then
    raise exception 'No tiene permiso para registrar cobros'
      using errcode = '42501';
  end if;

  if p_venta is null then
    raise exception 'La venta es obligatoria' using errcode = 'CV001';
  end if;

  select v.total, v.estado, c.habilita_cta_cte, coalesce(c.limite_credito, 0), v.cliente_id
    into v_total_venta, v_estado_venta, v_cliente_cta_cte, v_cliente_limite, v_cliente_id
    from public.ventas v
    join public.clientes c on c.id = v.cliente_id
   where v.id = p_venta
   for update of v, c;

  if not found then
    raise exception 'La venta no existe' using errcode = 'CV002';
  end if;

  if v_estado_venta <> 'Pendiente' then
    raise exception 'La venta no se encuentra Pendiente'
      using errcode = 'CV003';
  end if;

  if exists (select 1 from public.cobros_venta cv where cv.venta_id = p_venta) then
    raise exception 'La venta ya tiene un cobro registrado'
      using errcode = 'CV003';
  end if;

  if p_detalle is null
     or jsonb_typeof(p_detalle) <> 'array'
     or jsonb_array_length(p_detalle) = 0 then
    raise exception 'Debe indicar al menos un medio de pago'
      using errcode = 'CV001';
  end if;

  for v_item in select value from jsonb_array_elements(p_detalle)
  loop
    if jsonb_typeof(v_item) <> 'object' then
      raise exception 'Cada medio de pago debe ser un objeto válido'
        using errcode = 'CV001';
    end if;

    begin
      v_medio_id := nullif(btrim(v_item ->> 'medio_pago_id'), '')::uuid;
      v_monto := nullif(btrim(v_item ->> 'monto'), '')::numeric(14,2);
    exception
      when invalid_text_representation or numeric_value_out_of_range then
        raise exception 'El medio de pago o el monto no es válido'
          using errcode = 'CV001';
    end;

    if v_medio_id is null or v_monto is null or v_monto <= 0 then
      raise exception 'Todos los importes deben ser mayores a 0'
        using errcode = 'CV001';
    end if;

    select mp.nombre
      into v_medio_nombre
      from public.medios_pago mp
     where mp.id = v_medio_id
       and mp.activo = true
     for share;

    if not found then
      raise exception 'El medio de pago no existe o está inactivo'
        using errcode = 'CV002';
    end if;

    v_referencia := nullif(btrim(v_item ->> 'referencia'), '');
    if v_referencia is not null and char_length(v_referencia) > 100 then
      raise exception 'La referencia no puede superar los 100 caracteres'
        using errcode = 'CV005';
    end if;

    if lower(v_medio_nombre) = 'efectivo' then
      begin
        v_monto_recibido := nullif(btrim(v_item ->> 'monto_recibido'), '')::numeric(14,2);
      exception
        when invalid_text_representation or numeric_value_out_of_range then
          raise exception 'El monto recibido no es válido'
            using errcode = 'CV001';
      end;

      if v_monto_recibido is null or v_monto_recibido < v_monto then
        raise exception 'El monto recibido en efectivo debe cubrir el importe aplicado'
          using errcode = 'CV001';
      end if;
    else
      v_monto_recibido := null;
    end if;

    if lower(v_medio_nombre) like 'tarjeta%' then
      if v_referencia is null or v_referencia !~ '^[0-9]{4}$' then
        raise exception 'Para tarjeta indique únicamente los últimos 4 dígitos'
          using errcode = 'CV005';
      end if;
    elsif lower(v_medio_nombre) like 'transferencia%' and v_referencia is null then
      raise exception 'La referencia de la transferencia es obligatoria'
        using errcode = 'CV005';
    end if;

    if lower(v_medio_nombre) = 'cuenta corriente' then
      if not v_cliente_cta_cte then
        raise exception 'El cliente no está habilitado para cuenta corriente'
          using errcode = 'CV006';
      end if;

      -- Validación de Límite de Crédito
      if v_cliente_limite > 0 then
        v_saldo_actual := public.fn_saldo_cta_cte_cliente(v_cliente_id);
        if (v_saldo_actual + v_monto) > v_cliente_limite then
          raise exception 'Límite de crédito excedido. Límite: %, Saldo actual: %, Disponible: %',
            to_char(v_cliente_limite, 'FM999999999990.00'),
            to_char(v_saldo_actual, 'FM999999999990.00'),
            to_char(greatest(0::numeric(14,2), v_cliente_limite - v_saldo_actual), 'FM999999999990.00')
            using errcode = 'CV007';
        end if;
      end if;
    end if;

    v_total_aplicado := v_total_aplicado + v_monto;
  end loop;

  if v_total_aplicado <> v_total_venta then
    raise exception 'El total aplicado (%) no coincide con el total de la venta (%). Diferencia: %',
      to_char(v_total_aplicado, 'FM999999999990.00'),
      to_char(v_total_venta, 'FM999999999990.00'),
      to_char(abs(v_total_venta - v_total_aplicado), 'FM999999999990.00')
      using errcode = 'CV004';
  end if;

  insert into public.cobros_venta (venta_id, total, created_by)
  values (p_venta, v_total_venta, v_usuario)
  returning cobros_venta.id, cobros_venta.numero, cobros_venta.created_at
    into v_cobro_id, v_cobro_numero, v_cobro_fecha;

  for v_item in select value from jsonb_array_elements(p_detalle)
  loop
    v_medio_id := (v_item ->> 'medio_pago_id')::uuid;
    v_monto := (v_item ->> 'monto')::numeric(14,2);

    select mp.nombre into v_medio_nombre
      from public.medios_pago mp
     where mp.id = v_medio_id;

    v_referencia := nullif(btrim(v_item ->> 'referencia'), '');
    if lower(v_medio_nombre) = 'efectivo' then
      v_monto_recibido := (v_item ->> 'monto_recibido')::numeric(14,2);
      v_vuelto := v_monto_recibido - v_monto;
      v_referencia := null;
    else
      v_monto_recibido := null;
      v_vuelto := 0;
    end if;

    insert into public.detalle_cobro (
      cobro_id, medio_pago_id, monto, monto_recibido, vuelto, referencia
    ) values (
      v_cobro_id, v_medio_id, v_monto, v_monto_recibido, v_vuelto, v_referencia
    );
  end loop;

  return query
  select p_venta, v_cobro_id, v_cobro_numero, v_total_venta,
         v_cobro_fecha, v_usuario, true, v_estado_venta;
exception
  when unique_violation then
    raise exception 'La venta ya tiene un cobro registrado'
      using errcode = 'CV003';
end;
$$;

-- ----------------------------------------------------------------------------
-- 8. PERMISOS Y SEGURIDAD RLS
-- ----------------------------------------------------------------------------
alter table public.recibos_cobranza_cliente enable row level security;
alter table public.detalle_medio_recibo enable row level security;
alter table public.imputacion_recibo_venta enable row level security;

drop policy if exists "recibos_cobranza_select" on public.recibos_cobranza_cliente;
create policy "recibos_cobranza_select" on public.recibos_cobranza_cliente
  for select to authenticated using (public.es_usuario_interno());

drop policy if exists "detalle_medio_recibo_select" on public.detalle_medio_recibo;
create policy "detalle_medio_recibo_select" on public.detalle_medio_recibo
  for select to authenticated using (public.es_usuario_interno());

drop policy if exists "imputacion_recibo_venta_select" on public.imputacion_recibo_venta;
create policy "imputacion_recibo_venta_select" on public.imputacion_recibo_venta
  for select to authenticated using (public.es_usuario_interno());

revoke all on public.vw_cuenta_corriente_cliente from public, anon;
grant select on public.vw_cuenta_corriente_cliente to authenticated;

-- Primitiva interna: la usan obtener_resumen_cta_cte_cliente y registrar_cobro.
revoke all on function public.fn_saldo_cta_cte_cliente(uuid)
  from public, anon, authenticated;

revoke all on function public.obtener_resumen_cta_cte_cliente(uuid) from public, anon;
grant execute on function public.obtener_resumen_cta_cte_cliente(uuid) to authenticated;
revoke all on function public.listar_ventas_pendientes_cta_cte(uuid) from public, anon;
grant execute on function public.listar_ventas_pendientes_cta_cte(uuid) to authenticated;
revoke all on function public.registrar_recibo_cobranza(uuid, date, jsonb, jsonb, text) from public, anon;
grant execute on function public.registrar_recibo_cobranza(uuid, date, jsonb, jsonb, text) to authenticated;
revoke all on function public.registrar_cobro(uuid, jsonb) from public, anon;
grant execute on function public.registrar_cobro(uuid, jsonb) to authenticated;

-- ----------------------------------------------------------------------------
-- 9. EL CLIENTE WEB NO PUEDE CAMBIAR SUS CONDICIONES DE CRÉDITO
-- ----------------------------------------------------------------------------
-- Misma función que 0048 más las dos columnas nuevas: la policy clientes_update
-- deja que el cliente web actualice su propia fila (teléfono y email), y sin
-- esto podría subirse el límite de crédito o el plazo.
create or replace function public.fn_restringir_update_cliente_web()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if public.es_usuario_interno() then
    return new;
  end if;

  if (new.usuario_web_id is distinct from old.usuario_web_id
        and not (old.usuario_web_id is null and new.usuario_web_id = auth.uid()))
     or new.numero is distinct from old.numero
     or new.tipo_persona is distinct from old.tipo_persona
     or new.nombre is distinct from old.nombre
     or new.apellido is distinct from old.apellido
     or new.razon_social is distinct from old.razon_social
     or new.tipo_documento is distinct from old.tipo_documento
     or new.numero_documento is distinct from old.numero_documento
     or new.condicion_iva_id is distinct from old.condicion_iva_id
     or new.tipo_cliente_id is distinct from old.tipo_cliente_id
     or new.estado is distinct from old.estado
     or new.origen is distinct from old.origen
     or new.habilita_cta_cte is distinct from old.habilita_cta_cte
     or new.limite_credito is distinct from old.limite_credito
     or new.plazo_credito_dias is distinct from old.plazo_credito_dias
  then
    raise exception 'Un cliente web solo puede modificar su teléfono y su email'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

commit;
